### PR TITLE
fix link to service.js in branch_5_0_x

### PR DESCRIPTION
**Pull request by oetiker**

### CODE REVIEW

**Review by cajus — APPROVED** [review]

**Review by level420 — APPROVED** [review]

**Review by johnspackman — APPROVED** [review]

**Comment by derrell** [comment]
What is a valid {release_tag} ? I tried 5.0, 5.2, 5.0.2 and get 404 on all. I just want to verify that the new URL works...

**Comment by level420** [comment]
@derrell it's http://www.qooxdoo.org/5.0.1/tweets_step4.5/resource/tweets/service.js is working

**Comment by derrell** [comment]
LOL. So I surrounded a release tag that would have worked with all of my tries that didn't. Thanks.

**Review by derrell — APPROVED** [review]

**Comment by oetiker** [comment]
note the release_tag ist the git tag for the release (I assume) ... so it would be something like: https://raw.githubusercontent.com/qooxdoo/qooxdoo/release_5_0_2/component/tutorials/tweets/step4.5/source/resource/tweets/service.js

**Comment by level420** [comment]
4 approvals, documentation only
merging

**Comment by level420** [comment]
thank you @oetiker

**Pull request merged**
