### PR TITLE
Documentation added for Property 'isEqual' configuration key

### PR DESCRIPTION
**Pull request by schnepe2**
API documentation update for the new 'isEqual' configuration key (see #9039).

### CODE REVIEW

**Comment by derrell** [comment]
Great documentation. LGTM.

**Comment by schnepe2** [comment]
:confused: How can the code coverage **decrease** by adding comments?

**Comment by derrell** [comment]
There are more lines of "code" that are not being tested. :-( The coverage
numbers seem to me to be fairly useless as fine-grained measurements.

**Comment by level420** [comment]
LGTM. Should we merge?

**Comment by level420** [comment]
Merging.

**Comment by level420** [comment]
@schnepe2 Thank you!

**Pull request merged**
