### PR TITLE
[Bug 8824] Add support for dimensions provided in SVG files  - with different width/height units

### PR DESCRIPTION
**Pull request by ofilippov**
Add support for dimensions provided in SVG files
Support different units for height and width (px, in, cm, mm, pt, pc)

### CODE REVIEW

**Comment by cajus** [comment]
Cool! I was a bit lazy, because our SVG only were in px ;-) Didn't you need to patch the Image class to get proper sizes for SVG images?

**Comment by ofilippov** [comment]
@cajus I tested it a little (on checkbox component with my svg icons) and it works good - css width and height are specified correctly.

**Comment by cajus** [comment]
Hmm. Does not work here. The images are of zero width. If I add the explicit sizing it works. Strange.

**Comment by ofilippov** [comment]
@cajus do you have property "scale" enabled for your image?

**Comment by ofilippov** [comment]
I tried this file: https://www.iconfinder.com/icons/358219/download/svg/32
It works good for me - in both modes (scaled - when img node is used and non-scaled - when div)

**Comment by cajus** [comment]
The problem is that you don't want to set scale for all images. If you i.e. use the SVG in a qx.ui.form.Button, you've to set the "icon" childcontrol to "scale". That's why I've edited the Images class. So - yes, it works if you use scale, but it's not practical at all.

**Comment by ofilippov** [comment]
@cajus could you please share with me your example which doesn't work? Thanks!

**Comment by cajus** [comment]
Every SVG I try that comes right from Illustrator isn't recognized by your code. I'm allways getting

    Unable to get image info from file: /home/cajus/Projekte/svgtest/source/resource/svgtest/test.svg

when generating the source. When I use my code, it is detected correctly. Maybe I'll just add your DPI conversation method there.

If I go past this - without modifying Image.js, all SVGs I try with the basic demo generated by create_application.py just with a replaced image (test.png -> test.svg) produce a zero size Image in the button. If I patch Image.js with the stuff from my pull request it works. I'm using Google Chrome for the tests.

**Comment by cajus** [comment]
You seem to have mixed in your high resolution patch in this pull request.

**Comment by cajus** [comment]
Ok. Got a step further. After patching my code with your unit conversation function, it seems to work without a patched Image.js. That's interesting, because I don't see any difference in the generated data. What so ever. I've just modified my pull request to do the unit detection. So it works with your provided SVG and our designers SVGs.

**Comment by ofilippov** [comment]
@cajus I'm going to close my pull-request cause yours contains unit conversion part now (and this one is corrupted by another commit anyway). Thanks!

**Pull request closed without merging**
