### PR TITLE
Travis Simplified

### PR DESCRIPTION
**Pull request by oetiker**

### CODE REVIEW

**Comment by cajus** [comment]
Replace

script: PATH=`pwd`/phantomjs-2.1.1-linux-x86_64/bin/:$PATH tool/test/travis/run http://localhost:31323/framework/test-console/index-source.html

by

script: */bin/phantomjs tool/test/travis/run http://localhost:31323/framework/test-console/index-source.html

**Comment by oetiker** [comment]
at least there is no timeout anymore :)

**Comment by level420** [comment]
@oetiker Cool! You've managed to use the container based infrastructure! Congrats!

What about even caching the phantomjs binary?

https://github.com/zulip/zulip/pull/394/files

**Comment by oetiker** [comment]
good  idea :)

**Pull request merged**
