### PR TITLE
issue #9174: specific MS Edge focus event normalization handling

### PR DESCRIPTION
**Pull request by level420**
Fixes https://github.com/qooxdoo/qooxdoo/issues/9174

Please read comment https://github.com/qooxdoo/qooxdoo/issues/9174#issuecomment-247548311 for further eplanation.

### CODE REVIEW

**Comment by oetiker** [comment]
wow! congrats ... although ... I am wondering ... maybe at the base of the problem is edges false claim of sporting a webkit engine which it does not ... same thing with chromes blink ... maybe qooxdoo should face the music and distinguisch them ...

**Comment by level420** [comment]
@oetiker shure, we discussed this already partly in https://github.com/qooxdoo/qooxdoo/issues/8994 .

But this would mean walk through the whole framework and in a first step triple all the code declared behind ```.core.Environment.select("engine.name"``` and change code like
```javascript
qx.core.Environment.get("engine.name") == "webkit"
```
to
```javascript
qx.core.Environment.get("engine.name") == "engine"  ||
qx.core.Environment.get("engine.name") == "blink" ||
qx.core.Environment.get("engine.name") == "edgehtml"
```
and to make it really clean the IE engine is not "mshtml" but "trident".

All that is a lot of work and would for sure first destabilize the framework and make it incompatible to contributions and apps already out there.

I think this is something for version 7 a huge work and not something to fix issue #9174

**Comment by oetiker** [comment]
Yes you are totally right!  Thinking about it, I guess it might be better to leave that engine variable alone and create a new one called `engine-unmasked`. and then slowly start changing the code to use that ... because bigbang changes are soooo last year :)

**Comment by level420** [comment]
What about ```realengine``` ?

**Comment by level420** [comment]
I think we should create a issue about ```engine.realname``` (or whatever we will choose) and discuss this a bit.

Nonetheless I'd like to have this PR in, as it solves the issue.

After we have that ```engine.realname``` I'd be glad to change the code in ```qx.event.handler.Focus.js``` accordingly.

**Review by derrell — APPROVED** [review]

**Comment by level420** [comment]
:ballot_box_with_check: CALL FOR VOTE

**Review by johnspackman — APPROVED** [review]

**Review by zaucker — APPROVED** [review]
Fine with me.

**Comment by level420** [comment]
For further discussions on implementing ```engine.realname``` please follow up here: https://github.com/qooxdoo/qooxdoo/issues/8994#issuecomment-247585896

**Review by oetiker — APPROVED** [review]

**Review by hkollmann — APPROVED** [review]

**Review by cajus — APPROVED** [review]

**Pull request merged**
