### PR TITLE
Add a pullapprove.com config file

### PR DESCRIPTION
**Pull request by cboulanger**
See https://docs.pullapprove.com

### CODE REVIEW

**Review by hkollmann — APPROVED** [review]
What's this condition for
 - "not (files.exclude('docs/*.md') and files.exclude('documentation/*'))"?

**Comment by cboulanger** [comment]
If I have gotten this right, the logic would be: 

include in this group all commits of whichthe changed files
-  are in the "docs" folder and are markdown files or are in the "documentation" folder (`"files.include('docs/*.md') or files.include('documentation/*')"`) AND
- are not in folders that are OUTSIDE of these folders (`"not (files.exclude('docs/*.md') and files.exclude('documentation/*'))"`)
This should make sure that commits that concern both documentation AND code need the full quorum.

But maybe I have a logic mistake there? Do you have a better suggestion?

**Comment by hkollmann** [comment]
No i just want to understand the intention.

**Review by oetiker — APPROVED** [review]

**Review by derrell — APPROVED** [review]

**Review by johnspackman — APPROVED** [review]

**Review by level420 — APPROVED** [review]

**Comment by level420** [comment]
full quorum. merging.
thank you @cboulanger

**Pull request merged**
