### PR TITLE
add qxWeb support

### PR DESCRIPTION
**Pull request by hkollmann**

### CODE REVIEW

**Review by cboulanger — APPROVED** [review]

**Review by johnspackman — APPROVED** [review]

**Review by level420 — APPROVED** [review]

**Review by oetiker — APPROVED** [review]

**Comment by oetiker** [comment]
can we backport this to the 6 branch please ?

**Comment by hkollmann** [comment]
@oetiker : After merge?

**Review by derrell — COMMENTED** [review]
My only concern with this is that none of us on the team use qxWeb, so turn around on finding regressions may be long...

**Comment by oetiker** [comment]
@derrell I am using it :)

**Comment by hkollmann** [comment]
@derrell: I agree - but discussion on gitter shows that there are people who use it. 
IMHO we will not support it. Just compile it.

**Comment by oetiker** [comment]
not the website bits but the event and dom selection machinery ... which is also used by qx desktop btw, just hidden away

**Review by derrell — APPROVED** [review]

**Pull request merged**
