### PR TITLE
store listener unique ids added in addListenerOnce

### PR DESCRIPTION
**Pull request by fortooon**
store listener unique ids added in addListenerOnce to remove all listeners correctly.

Bug in MEvent.addListenerOnce() for multiple times call with same args #9627

### CODE REVIEW

**Comment by fortooon** [comment]
Sorry, master has a code that differs from branch_5_0_X.  I need to be more careful later.

**Comment by hkollmann** [comment]
Why did you close this? It should come to the current master.

**Comment by cboulanger** [comment]
@fortooon Can you resolve the conflicts and have a look at the failing tests? 
Thank you!

**Comment by oetiker** [comment]
@fortooon ping

**Comment by hkollmann** [comment]
found a much simpler solution

**Pull request closed without merging**
