### PR TITLE
Let the build fail if the linter has a problem

### PR DESCRIPTION
**Pull request by cajus**
The first test run will fail currently. At least until #9009 is merged.

### CODE REVIEW

**Comment by oetiker** [comment]
I like it!

**Comment by oetiker** [comment]
#9009 is merged, but I think it still fails ... relaunching the tests

**Comment by level420** [comment]
@oetiker, @cajus: what is the state of this PR. I'd like to have lint run in as well.

**Comment by cajus** [comment]
From my point of view, it's ok to give it a go.

**Comment by oetiker** [comment]
ok I merge

**Pull request merged**
