### PR TITLE
 Adding a new function to get the full model array with no changes (with indentation)

### PR DESCRIPTION
**Pull request by nwgroup**
Thanks for your review

### CODE REVIEW

**Review by derrell — APPROVED** [review]

**Review by derrell — COMMENTED** [review]
This should probably be a squash commit, with so many commits here to do a few -line change...

**Comment by nwgroup** [comment]
Derrel sorry, we start today to use GitHub. Thanks in advance and we are happy to connect with the team and to meet you.

**Comment by derrell** [comment]
Not a problem, @nwgroup. Using git takes some practice, and github adds a bit of extra learning to the mix.

From a different project, this looks like a pretty good tutorial on doing a squash:
 https://github.com/todotxt/todo.txt-android/wiki/Squash-All-Commits-Related-to-a-Single-Issue-into-a-Single-Commit

**Review by johnspackman — APPROVED** [review]

**Review by hkollmann — APPROVED** [review]

**Review by cajus — APPROVED** [review]

**Review by level420 — APPROVED** [review]

**Comment by hkollmann** [comment]
to get a new check job

**Comment by hkollmann** [comment]
3 days, 5 approves, merged
Thanks, @nwgroup

**Pull request merged**
