### PR TITLE
Update Model.js

### PR DESCRIPTION
**Pull request by Holdwyn**
The event system creates a exponential runtime when rendering a table. Huge tables (especially with dozen of columns) let the browser become unresponsive.
This fixes the problem by delaying the event until everything ist set.

### CODE REVIEW

**Review by cboulanger — APPROVED** [review]

**Review by level420 — APPROVED** [review]

**Review by oetiker — APPROVED** [review]

**Review by hkollmann — APPROVED** [review]

**Review by derrell — APPROVED** [review]
Awesome!!!

**Comment by hkollmann** [comment]
Could you prepare a PR for latest too? Many thanks!

**Comment by hkollmann** [comment]
Thanks @Holdwyn !

**Comment by Holdwyn** [comment]
> Could you prepare a PR for latest too? Many thanks!
> #10304 <

**Pull request merged**
