### PR TITLE
Fix for #9620: Resizing a table column while any cell is being edited, resizes the editor even when in a different column.

### PR DESCRIPTION
**Pull request by lucapivato**

### CODE REVIEW

**Review by cboulanger — APPROVED** [review]

**Review by johnspackman — APPROVED** [review]

**Review by hkollmann — APPROVED** [review]

**Review by cajus — APPROVED** [review]

**Review by derrell — APPROVED** [review]

**Review by level420 — APPROVED** [review]

**Comment by level420** [comment]
Full approval! merging.
thank you @lucapivato

**Comment by level420** [comment]
Oh damn! forgot @oetiker. Sorry about that. But he is still in vacation?

**Comment by derrell** [comment]
He's still posting beautiful images of paradise on Facebook, as of a day or so ago.

**Comment by level420** [comment]
Well then it's not such a big problem. I'll be more carefully in the future.

**Pull request merged**
