### PR TITLE
[BUG #8558] Add support for the fullscreen API

### PR DESCRIPTION
**Pull request by cajus**
Although it works on all tested (current) browsers, the API is marked experimental and
browser support for fullscreen attributes is quite messed up.

http://bugzilla.qooxdoo.org/show_bug.cgi?id=8558

### CODE REVIEW

**Comment by tobiasoberrauch** [comment]
Hi. Thank you for helping us to extend qooxdoo.
What happens to this commit "Merge branch 'master' into fullscreen-api"
I can't merge this PR because it contains to many files (https://github.com/cajus/qooxdoo/commit/786d60ed5e4b56cba214efc7d8a361dfd578d212)
Could you help me, please: Contains this commit (https://github.com/cajus/qooxdoo/commit/2bc6967bef587332a99e89c9153c2f5d2b10a883) all of your changes?

Cheers Tobias

**Comment by cajus** [comment]
Hi Tobias. Maybe the merge with master was no good idea, but that should not make any difference. No idea where the problem is.

What you need is ccd42d0 (the initial one) and 2bc6967 (which makes the changes requested by Martin).

Hope that helps. If you want to, I can create another pull request without the merges. Just drop a note.

**Comment by wittemann** [comment]
Another one would be great so we can get that in asap. :)

**Comment by wittemann** [comment]
We should use the new pull request --> closing this one.

**Pull request closed without merging**
