### PR TITLE
Virtual list page scroll

### PR DESCRIPTION
**Pull request by derrell**
Enable PageUp and PageDown to operate by pages. (Was never really implemented)

PageUp and PageDown were "implemented" as moving to the first or last
selectable item in the list. This implements proper full-pane paging when
PageUp or PageDown are pressed.

Suggest squash when merging.

### CODE REVIEW

**Review by cboulanger — APPROVED** [review]

**Review by hkollmann — APPROVED** [review]

**Review by oetiker — APPROVED** [review]

**Review by johnspackman — APPROVED** [review]

**Comment by hkollmann** [comment]
@derrell Ping?

**Comment by derrell** [comment]
@hkollmann I don't see this waiting on me for anything. Am I missing something?

**Comment by hkollmann** [comment]
Deleting of oldItem in Row.js to make the linter happy

**Comment by derrell** [comment]
Doh! Sorry. Should be fixed now.

**Review by zaucker — APPROVED** [review]

**Pull request merged**
