### PR TITLE
Wrong blocker positioning

### PR DESCRIPTION
**Pull request by evandropoa**
Blocker's are added as child of a root or a layout content element and have it's position set to absolute, so just needs to be positioned to the top/left of its parent with 100% of its width/height to cover it (#10411) and dont need move/resize

https://tinyurl.com/mpfk2yvk

### CODE REVIEW

**Comment by lucapivato** [comment]
Would it be possible to change the literals to double quotes?

**Comment by oetiker** [comment]
Looking at the code which adds the blocker: 

https://github.com/qooxdoo/qooxdoo/blob/326fba0ccfcc5c30e58ddbca0504dab4e8ab7cf1/source/class/qx/ui/core/Blocker.js#L151

it seems that it gets added into the same PARENT as the widget it is blocking ... so it seems odd that the parent should have exactly the same size as the widget it is blocking ... at least not in a general sense ... 

in the sample code the content element may be nested and that is why it works ?

**Comment by evandropoa** [comment]
> 

I see what you are talking about, I just dont follow why it should be added to the parent if I want to block a specific widget.

**Comment by evandropoa** [comment]
> > 
> 
> I see what you are talking about, I just dont follow why it should be added to the parent if I want to block a specific widget. Absolute position its absolute in relation to its container, in the button example, the content element its the button content, if you move the blocker (already in container relation) it will be offset what is wrong.

Maybe what's wrong is that it's not getting the parent container element, it should get container element window body or document root in the examples?
```
 this._widget
          .getLayoutParent()
          .getContentElement()
```

**Pull request closed without merging**
