### PR TITLE
Added flag for static methods to be shown in api viewer

### PR DESCRIPTION
**Pull request by goldim**
Not sure if it is done for static variables too.

### CODE REVIEW

**Comment by johnspackman** [comment]
Do we need this flag?  The list of statics are output separately to the members so the API viewer can already distinguish between the two.  Doing it that way is essential because you can have a static method and a member method with the same name (it would be bad practice IMHO but it's allowed).

**Comment by goldim** [comment]
@johnspackman in API viewer checked against this flag for static methods but this flag is absent for static methods in meta right now. I added the `isStatic` flag to each static method there in API viewer to work around the problem.

**Review by derrell — APPROVED** [review]

**Review by oetiker — APPROVED** [review]

**Comment by johnspackman** [comment]
I see what you mean now about isStatic in https://github.com/qooxdoo/qxl.apiviewer/blob/master/source/class/qxl/apiviewer/dao/Class.js#L129

I prefer your original version - because the API viewer is already mapping that data into the meta data, which is what *it* needs rather than the compiler needs (ie from the compiler's point of view the data is already correct and sufficient for its purpose, and it feels a little wrong to modify the output structure because it's slightly more convenient for an app to consume); this is also a duplication of information in the output, and we can't resolve it by merging the list of methods into one list to remove that duplication.

**Review by hkollmann — APPROVED** [review]

**Comment by goldim** [comment]
@johnspackman I agree excessive info is bad then I just close this PR?

**Pull request closed without merging**
