### PR TITLE
Move to sass

### PR DESCRIPTION
**Pull request by hkollmann**
see https://github.com/qooxdoo/qooxdoo/issues/10146.
I found a way to trick out the sass loading problem.
This should solve all node-sass problems.

Should be backportet to compiler

### CODE REVIEW

**Review by cboulanger — APPROVED** [review]
This is excellent, thank you very much!

**Comment by johnspackman** [comment]
Does this solve the compatibility problem with jsdom?

**Comment by hkollmann** [comment]
> Does this solve the compatibility problem with jsdom?

Not in generally. It solves the problem loading sass in qooxdoo compiler. We do not use jsdom there - we use outr own generated windows problem.

You can use this approach to load sass with jsdom. I have'nt tried it it.
The idea is to trick out sass:

  process.versions.electron = "0.0.0";     Tells sass that we are in a node enviroment
  window.document.currentScript = {src: ""}; Prevents sass to access to the document.scripts variable

**Comment by oetiker** [comment]
sass seems quite a bit slower ... but then again, I guess we do not have a performance problem there, or do we?
https://www.peterbe.com/plog/quick-comparison-between-sass-and-node-sass

**Review by oetiker — APPROVED** [review]

**Review by level420 — APPROVED** [review]

**Review by derrell — APPROVED** [review]

**Review by johnspackman — APPROVED** [review]

**Pull request merged**
