### PR TITLE
Enable automatic manifest fonts

### PR DESCRIPTION
**Pull request by cajus**
In combination with the qx.compiler, this patch enables the use of
icon fonts that have been defined in the Manifest.json.

That would allow either font packages or "single point of config"
icon fonts.

Related to the discussion in https://github.com/qooxdoo/qooxdoo-compiler/issues/24

### CODE REVIEW

**Review by johnspackman — APPROVED** [review]

**Comment by oetiker** [comment]
@cajus is there documentation describing the behavior ?

**Comment by cajus** [comment]
@oetiker I updated the documentation for the manifest in qx-compiler. Currently I'm updating the documentation in the main qx repo. Will add the commit in some minutes...

**Review by oetiker — APPROVED** [review]
great

**Review by cboulanger — APPROVED** [review]

**Comment by level420** [comment]
@cajus does this PR break compatibility with the current generator.py font support?

**Comment by cajus** [comment]
@level420 no. The "old" stuff still works. But it needs the additional *Font* definition in your theme.

**Review by level420 — APPROVED** [review]

**Review by derrell — APPROVED** [review]

**Comment by level420** [comment]
5 approvals, merging.
thank you @cajus

**Pull request merged**
