### PR TITLE
TreeVirtual - Allow prevention of specific node editing

### PR DESCRIPTION
**Pull request by rad-pat**
Following on from my changes to allow node editing - I wanted to be able to have some nodes read-only. This change allows you to set the bCanEdit member, which is set to true by default, to false if you want to prevent an edit via the setState() method. Pretty simple, the editor just checks the value and if false no cell editor is generated so the edit is not started.

### CODE REVIEW

**Review by derrell — APPROVED** [review]

**Review by cboulanger — APPROVED** [review]

**Review by level420 — APPROVED** [review]

**Review by hkollmann — APPROVED** [review]

**Comment by hkollmann** [comment]
Could you fix the lint issue please?

**Comment by hkollmann** [comment]
And merge with master?

**Comment by rad-pat** [comment]
Fixed+merged with master

**Review by oetiker — APPROVED** [review]

**Comment by hkollmann** [comment]
Thanks @rad-pat !

**Pull request merged**
