### PR TITLE
icon fonts are not necessarly square

### PR DESCRIPTION
**Pull request by oetiker**
take the aspect ratio of the glyphs into account when displaying an iconfont

### CODE REVIEW

**Review by cboulanger — DISMISSED** [review]

**Review by hkollmann — APPROVED** [review]

**Review by hkollmann — CHANGES_REQUESTED** [review]
could you fix the lint error please:

..........................................................[Sat May  5 15:08:27 2018] 127.0.0.1:39686 [200]: /source/resource/qx/icon/Tango/16/places/folder.png?1525532907348

..

..

Firefox 59.0.0 (Linux 0.0.0) qx.test.ui.basic Image:testWebFontImage FAILED

	Expected '20px' but found 'nullpx'!

		qx.core.AssertionError.constructor:326

		qx.core.Assert.__fail:1179

		qx.core.Assert.assertEquals:4808

		qx.type.BaseString.assertEquals:779

		qx.test.ui.basic.Image.testWebFontImage:7

		qx.dev.unit.TestFunction:1438

		qx.dev.unit.TestResult.run:5892

		qx.dev.unit.TestFunction.run:1287

		.runTest://travis-job-qooxdoo-qooxdoo-375288884.travisci.net:9876node_modules/karma-qooxdoo/qooxdoo-adapter.js

...........[Sat May  5 15:08:29 2018] 127.0.0

**Review by johnspackman — DISMISSED** [review]

**Comment by oetiker** [comment]
I think I found the missing bit ...

**Review by johnspackman — DISMISSED** [review]

**Comment by hkollmann** [comment]
Lint problem still exists 😒

**Comment by oetiker** [comment]
now th tests seem more happy

**Review by hkollmann — APPROVED** [review]

**Review by cboulanger — APPROVED** [review]

**Review by level420 — APPROVED** [review]

**Review by johnspackman — APPROVED** [review]

**Review by cajus — APPROVED** [review]

**Comment by johnspackman** [comment]
5 approvals, merging, thank you @oetiker !!

**Pull request merged**
