### PR TITLE
make automatic memory management switchable, default to enabled

### PR DESCRIPTION
**Pull request by johnspackman**

### CODE REVIEW

**Comment by oetiker** [comment]
... and the migrator will then disable it ?

**Comment by johnspackman** [comment]
no, this is the PR to master so it's just enabled by default and there's nothing for the migrator to enable; there is a separate PR for the `maintenance` branch that makes it disabled by default.  The maintenance branch becomes the 5.1 release.

(in hindsight, for a better commit history I probably should have done this and then a separate branch to disable it for `maintenance`, but actually I just cherry picked)

**Review by derrell — APPROVED** [review]

**Comment by level420** [comment]
@johnspackman tests fail on all browsers with 
qx.test.core MemoryManagement:testEnvSetting FAILED

**Review by oetiker — APPROVED** [review]

**Review by level420 — APPROVED** [review]

**Review by zaucker — APPROVED** [review]
Please add a newline at the end of MemoryManagement.js

**Comment by johnspackman** [comment]
@zaucker no problemo :)

**Review by cajus — APPROVED** [review]

**Comment by cajus** [comment]
Five approvals. Merging. Thanks @johnspackman ;-)

**Pull request merged**
