### PR TITLE
Update travis to skip tests for documentation commits

### PR DESCRIPTION
**Pull request by cboulanger**
This will skip tests for commits/PRs that contain "documentation" or "docs" either in the commit message or in the branch name. This is necessary so that documentation updates do not have to wait for completely needless tests to finish.

### CODE REVIEW

**Comment by cboulanger** [comment]
Unfortunately, it doesn't seem to be possible for Travis to check the paths of the files that are part of the commit. This would have allowed a completely automatic solution. With this, you still have to make sure to include "docs" or "documentation" in either the branch name or all commit messages of the commits that are pushed.

**Review by derrell — DISMISSED** [review]
I'm concerned about this. I think we're going to end up with false positives on commit messages... But I'm not sure what to do with it if it's not otherwise possible to simply look at the paths. Sigh.

**Comment by cboulanger** [comment]
We could also check the branch name only and not look at the commit message, if that seems safer to you.

**Comment by johnspackman** [comment]
sorry if this is a dumb question because I simply don't understand the travis syntax, but does this mean that if I have a commit message which is "fixed bug with blah and updated documentation to match" I would hit this travis rule?

I've no problem with these kind of parsing filters, but maybe we should use a specific syntax - eg "[travis-docs-only]"

**Comment by cboulanger** [comment]
@johnspackman You're right, that kind of commit message would match the filter. Maybe we require a more specific code word like the one you suggested. I'll fix it.

**Review by oetiker — CHANGES_REQUESTED** [review]
another option would be to use 

https://github.com/ITISFoundation/osparc-simcore/blob/master/ops/travis/helpers/test_for_changes

this has the advantage that it actually tests which files have changed. relying on comments seems a bit error-prone and might lead to tests not running by accident.

you can see the script in use here

https://github.com/ITISFoundation/osparc-simcore/blob/master/ops/travis/unit-testing/frontend

and ultimately like this in the `.travis.yml`

```yml
# frontend testing ----------------------------------------------------------------------
    - stage: build / unit-testing
      name: front end testing
      language: node_js
      node_js:
        - "10"
      addons:
        apt:
          packages:
            - libgconf-2-4

      before_install:
        - bash ops/travis/unit-testing/frontend before_install
      install:
        - bash ops/travis/unit-testing/frontend install
      before_script:
        - bash ops/travis/unit-testing/frontend before_script
      script:
        - bash ops/travis/unit-testing/frontend script
      after_success:
        - bash ops/travis/unit-testing/frontend after_success
      after_failure:
        - bash ops/travis/unit-testing/frontend after_failure

      deploy:
        # https://docs.travis-ci.com/user/deployment/pages/
        provider: pages
        target-branch: master
        # Set in travis-ci.org dashboard, marked secure
        github-token: $GH_PAGES_TOKEN
        skip-cleanup: true
        keep-history: false
        local-dir: itisfoundation.github.io
        repo: ITISFoundation/itisfoundation.github.io
        verbose: true
        on:
          repo: ITISFoundation/osparc-simcore
          branch: master
```

**Comment by cboulanger** [comment]
@oetiker How does this work with stages? Can we go with my solution first and then replace it with something better later- the current situation is bad, we need to wait hours for simple doc changes...

**Comment by cboulanger** [comment]
@oetiker I like your solution because we'll be able to detect if the changes concern documentation *only* without the committer having to provide special meta information in the branch name or commit message. But as I said, I suggest we put a simple solution in place now until we find the time to write a more adequate one.

**Review by level420 — APPROVED** [review]

**Review by johnspackman — APPROVED** [review]

**Review by hkollmann — APPROVED** [review]
Lets commit this yet and add a better solution later!

**Review by derrell — APPROVED** [review]

**Review by oetiker — APPROVED** [review]

**Comment by cboulanger** [comment]
This might be useful:
https://github.com/RReverser/react/commit/233af7e2dff4c79619f5cda6943388ff9e21581b

**Comment by cboulanger** [comment]
Or this: https://github.com/dev-id/Magic-Spoiler/blob/8111a06ab6682e020169991d5e2aa4fa503d787f/preflight.sh

**Comment by cboulanger** [comment]
Let's continue over here: #9683

**Pull request merged**
