### PR TITLE
Unified webfonts fix 2

### LINKED ISSUE #10586: Font Icons don't work in table cells
Since qooxdoo of version 7.6.0 font icons don't work in table cells. Instead of them just rectangles are shown like on the image:

Снимок экрана от 2023-04-17 15-42-46

To reproduce it just take this snippet and paste into playground:
```javascript
function createRandomRows(rowCount) {
  var rowData = [];
  var now = new Date().getTime();
  var dateRange = 400 * 24 * 60 * 60 * 1000; // 400 days
  var nextId = 0;
  for (var row = 0; row < rowCount; row++) {
    var date = new Date(now + Math.random() * dateRange - dateRange / 2);
    rowData.push([ nextId++, Math.random() * 10000, date, (Math.random() > 0.5), "@MaterialIcons/notifications/24" ]);
  }
  return rowData;
}


// window
var win = new qx.ui.window.Window("Table").set({
  layout : new qx.ui.layout.Grow(),
  allowClose: false,
  allowMinimize: false,
  contentPadding: 0
});
this.getRoot().add(win);
win.moveTo(30, 40);
win.open();

// table model
var tableModel = new qx.ui.table.model.Simple();
tableModel.setColumns([ "ID", "A number", "A date", "Boolean", "Icon Font" ]);
tableModel.setData(createRandomRows(1000));

// make second column editable
tableModel.setColumnEditable(1, true);

// table
var table = new qx.ui.table.Table(tableModel).set({
  decorator: null
});
win.add(table);

var tcm = table.getTableColumnModel();

// Display a checkbox in column 3
tcm.setDataCellRenderer(3, new qx.ui.table.cellrenderer.Boolean());
var renderer = new qx.ui.table.cellrenderer.Image();
table.getTableColumnModel().setDataCellRenderer(4, renderer);

// use a different header renderer
tcm.setHeaderCellRenderer(2, new qx.ui.table.headerrenderer.Icon("icon/16/apps/office-calendar.png", "A date"));
 ```

### PR DESCRIPTION
**Pull request by johnspackman**
Fixes https://github.com/qooxdoo/qooxdoo/issues/10586 

Also fixes multiple validators for one font and uses browser FontFaceSet api in preference to timeouts to detect if a font is ready

### CODE REVIEW

**Review by cboulanger — APPROVED** [review]

**Review by goldim — CHANGES_REQUESTED** [review]
The bell icon seems like to be descended:

image

**Review by goldim — APPROVED** [review]

**Review by goldim — CHANGES_REQUESTED** [review]
Tests related with fonts are failed

**Review by level420 — APPROVED** [review]

**Review by derrell — APPROVED** [review]

**Review by oetiker — APPROVED** [review]

**Comment by hkollmann** [comment]
@johnspackman: did you find some time to fix the tests?

**Review by goldim — APPROVED** [review]

**Comment by hkollmann** [comment]
Thanks @johnspackman !

**Pull request merged**
