### PR TITLE
return promise in start function 

### PR DESCRIPTION
**Pull request by hkollmann**
so that it can be used in async/await context

### CODE REVIEW

**Review by derrell — DISMISSED** [review]

**Review by cboulanger — CHANGES_REQUESTED** [review]
Can you document the return value type?

**Comment by hkollmann** [comment]
of Course ...

**Review by cboulanger — APPROVED** [review]

**Comment by level420** [comment]
It seems that the travis run fails for some internal problems. I like most the following message in the logs:
```
Encrypted environment variables have been removed for security reasons.
```

**Comment by level420** [comment]
@hkollmann does promisifying the start method somehow change the non promise usage of the script loader? I'm not as familiar with promises as I should be, so my main concern is that it changes something for existing apps not using promises.

**Comment by hkollmann** [comment]
No you can use the start method as before an just ignore the result

**Review by johnspackman — APPROVED** [review]

**Review by level420 — APPROVED** [review]

**Review by oetiker — APPROVED** [review]

**Review by cajus — APPROVED** [review]

**Comment by level420** [comment]
5 approvals, more than 3 business days, merging
thank you @hkollmann

**Pull request merged**
