### PR TITLE
[Bug 8841] qx.ui.table.paneScroller startEditing: scrollCellVisible first argument is the column index, not the columns x position

### PR DESCRIPTION
**Pull request by level420**
Fix proposed by Maxim Fedyashev.

See http://bugzilla.qooxdoo.org/show_bug.cgi?id=8841

### CODE REVIEW

**Comment by level420** [comment]
@ecker: would you please be so kind to merge this one?

Thank you.

**Comment by level420** [comment]
@ecker What is the current state of qooxdoo? What about the announced license change? Please give us some feedback!

**Comment by oetiker** [comment]
thanks!

**Comment by level420** [comment]
Thank you Tobi!

**Comment by ecker** [comment]
@level420: the changes regarding license, etc. are ongoing. There gonna be updates soon. Thanks for contributing as we're getting more productive by incorporating pull requests an the likes.

**Pull request merged**
