### PR TITLE
fix link to service.js in master

### PR DESCRIPTION
**Pull request by oetiker**

### CODE REVIEW

**Review by cboulanger — DISMISSED** [review]

**Comment by level420** [comment]
@oetiker what's the difference between this PR and #9409 ?

**Review by level420 — APPROVED** [review]

**Comment by level420** [comment]
Ah OK this PR is for master and the other is for 5.0.2

**Review by cboulanger — APPROVED** [review]

**Comment by level420** [comment]
2 approvals, documentation only
merging

**Comment by level420** [comment]
thank you @oetiker

**Pull request merged**
