### PR TITLE
final vote for publishing v7

### PR DESCRIPTION
**Pull request by hkollmann**

### CODE REVIEW

**Review by cboulanger — APPROVED** [review]
@hkollmann Thanks for pushing the release forward!

**Review by oetiker — APPROVED** [review]

**Review by derrell — CHANGES_REQUESTED** [review]
Found some typos in the release docu. See #10369.

Is there a release checklist that we should use to confirm everything is in place prior to the release?

**Comment by hkollmann** [comment]
https://github.com/qooxdoo/qooxdoo/issues/10342

**Comment by derrell** [comment]
Thanks. I fixed a couple of typos in the history file as well, added to #10369.

**Review by johnspackman — APPROVED** [review]

**Comment by hkollmann** [comment]
BTW: releasing a
 Patch Version will be qx pkg publish once we have released it

**Review by level420 — APPROVED** [review]
:thumbsup: Thank you for your work! Great!

**Review by derrell — APPROVED** [review]

**Pull request merged**
