### PR TITLE
Added ISO8601 parsing support to qx.lang.normalize.Date #7175

### PR DESCRIPTION
**Pull request by schnepe2**
This is the (2nd) PR in response to the discussion at #9134

### CODE REVIEW

**Comment by pcdummy** [comment]
Nice one.

**Comment by schnepe2** [comment]
I would have added a :+1: vote, 'cause initially this PR was from @gnikolaidis,
but I believe this would be considered as a "self-vote" :smile:

**Comment by gnikolaidis** [comment]
On the other hand, I am free vote without breaking the law :-)

**Comment by level420** [comment]
Three votes, more than 2 business days.
Merging.
Thank you @schnepe2

**Pull request merged**
