### PR TITLE
minor fixes for simple theme and virtual widgets

### PR DESCRIPTION
**Pull request by johnspackman**

### CODE REVIEW

**Review by hkollmann — APPROVED** [review]

**Review by derrell — COMMENTED** [review]
I'm wondering if these are going to be non-BC changes to users apps? It's changing the default appearance, and apps may not want those changes...???

**Comment by derrell** [comment]
If documented, and released in v8, that'd be fine. For a v7.x point release, I'm not so sure.

**Comment by johnspackman** [comment]
the appearances are missing, so the virtual components just have an absence of styling when using the simple theme- this just gives them something

**Review by cboulanger — APPROVED** [review]

**Review by oetiker — APPROVED** [review]

**Review by hkollmann — APPROVED** [review]

**Review by derrell — APPROVED** [review]

**Review by level420 — APPROVED** [review]

**Comment by hkollmann** [comment]
Thanks @johnspackman !

**Pull request merged**
