### PR TITLE
add option to disable tab navigation, activated by default.

### PR DESCRIPTION
**Pull request by peuter**
We are using the monaco text editor to edit Text files. With this new option you can avoid the behavior that the editor is loosing focus when you press the tab key.

### CODE REVIEW

**Review by hkollmann — APPROVED** [review]

**Review by cboulanger — APPROVED** [review]

**Review by derrell — APPROVED** [review]

**Review by oetiker — APPROVED** [review]

**Review by johnspackman — APPROVED** [review]

**Comment by hkollmann** [comment]
@peuter : Can't merge - the branch is out of date. Could you do the update?

**Comment by hkollmann** [comment]
@peuter : Sorry you must do this again because i merged your first PR

**Review by johnspackman — APPROVED** [review]

**Review by level420 — APPROVED** [review]

**Comment by hkollmann** [comment]
@peuter : Could you merge once again? I can'nt and do  not know why

**Comment by level420** [comment]
@peuter normally we (the maintainers) are able to push the changes from master back to your branch. but I think you've not allowed changes by the maintainers in your branch which leads to the situation that we need to ask you to do so. There is a checkbox for PRs which toggles the permissions. See https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/allowing-changes-to-a-pull-request-branch-created-from-a-fork#enabling-repository-maintainer-permissions-on-existing-pull-requests

**Comment by peuter** [comment]
> @peuter normally we (the maintainers) are able to push the changes from master back to your branch. but I think you've not allowed changes by the maintainers in your branch ...

Unfortunately I do not see this option anywhere, so I am not able to set it. I guess it' s because I created this PR not from an user owned fork, but from our projects fork.

**Pull request merged**
