### PR TITLE
Prepare alpha release of NPM module qooxdoo-sdk

### PR DESCRIPTION
**Pull request by cboulanger**
This adds the "files" property to `package.json` which restricts publication to the "framework"-folder (the rest of the package is not needed).

### CODE REVIEW

**Review by cajus — APPROVED** [review]
I can't tell if that is good or bad. Never used 'file' in package.json before. So I'm fully trusting @cboulanger that it's the way to go ;-)

**Comment by cajus** [comment]
Maybe it could be rebased to just contain one commit, though.

**Comment by level420** [comment]
@cajus is rebasing in this case needed if we use "Squash and merge" to merge it?

**Review by level420 — APPROVED** [review]
I'm trusting in @cboulanger

**Comment by cboulanger** [comment]
@cajus @level420 Thank you for your trust! I have faith in the [NPM docs] (https://github.com/npm/npm/wiki/Files-and-Ignores#files), since I haven't used the property yet, either :-)

**Comment by cajus** [comment]
@level420 I meant `git rebase -i <commit-ref-before-the-pr>` and then squash everything before. Just to get rid of the 'merge'.

**Comment by cboulanger** [comment]
@cajus I'll make sure to rebase before doing the PR next time, but if we can squash and merge through GitHub, I'd prefer that for the moment...

**Comment by cajus** [comment]
Perfect ;-)

**Review by hkollmann — COMMENTED** [review]
Not enough.  The stuff in Framework is'nt needed. Only the framework/source folder.

I was just working on this - but found that there is not proper readme on npmjs. My intention was to fix this first. See https://github.com/qooxdoo/qooxdoo/issues/9456

**Comment by hkollmann** [comment]
Yes, i think so. I found some npm docs how to test and i want to workthrouh. This Task is next on my list

**Comment by cboulanger** [comment]
Closing this. See the general discussion here:  #9369 and specific issues like #9456 and #9450 which should be brought together.

**Pull request closed without merging**
