### PR TITLE
Test for a documentation PR

### PR DESCRIPTION
**Pull request by cboulanger**
[travis-docs-only]

Expected:
- test suite should not run
- only two approvals should be necessary

### CODE REVIEW

**Review by derrell — APPROVED** [review]

**Comment by cboulanger** [comment]
The Travis test is stuck. I wonder why this is. Maybe it is because in the current scenario, non of the travis stages run, since none of their conditions are met:

https://github.com/qooxdoo/qooxdoo/blob/master/.travis.yml#L31-L39

But it seems strange to me that it would just stall, instead of erroring or passing.

**Comment by derrell** [comment]
It looks like it may be deadlocked. Travis is waiting on pullapprove, and pullapprove is waiting on travis.

**Comment by cboulanger** [comment]
We might have to migrate Travis integration from "GitHub Services" to "GitHub Apps" for this to work: https://docs.travis-ci.com/user/migrate/legacy-services-to-github-apps-migration-guide/ . I think only @oetiker can do this?

**Review by cboulanger — COMMENTED** [review]
(deleted)

**Review by johnspackman — APPROVED** [review]

**Review by hkollmann — APPROVED** [review]

**Review by oetiker — APPROVED** [review]

**Comment by cboulanger** [comment]
This implements issue #9683 now. However, it fails with a connection error to saucelabs.

**Review by level420 — APPROVED** [review]

**Pull request merged**
