### PR TITLE
Fix 10398: const ol = require("ol") gives exception

### PR DESCRIPTION
**Pull request by hkollmann**

### CODE REVIEW

**Review by derrell — APPROVED** [review]

**Review by cboulanger — APPROVED** [review]

**Review by johnspackman — APPROVED** [review]
no problem with the PR, but just wanted to ask if it was intended to have only this change in it?  IE does this fix https://github.com/qooxdoo/qooxdoo/issues/10398 ?  nI can't find any docs for the `global` config option

**Comment by derrell** [comment]
The docs, limited as they are, for `global` are in https://www.npmjs.com/package/browserify. Search for `opts.global` to skip a bunch of unrelated hits. And yes, it fixes #10398.

**Comment by derrell** [comment]
I had not comprehended the meaning of that option, so had not tried it.

**Comment by hkollmann** [comment]
Found it here https://stackoverflow.com/a/56608843 and just tried it

**Comment by hkollmann** [comment]
Here is the explantion of global: https://github.com/babel/babelify#why-arent-files-in-node_modules-being-transformed 
not very helpfull

**Comment by derrell** [comment]
lol @hkollmann. With https://github.com/qooxdoo/qooxdoo/pull/10400/commits/af7b932a526870defeabfabcb18c7b5e073a2520, you're acting like the US Congress, and sneaking in a completely unrelated clause to a "bill", in hopes that no one will notice :-)

**Comment by hkollmann** [comment]
Sorry.
I found this issue during compiling my multi target project. It's just in the same workflow for me.

**Review by johnspackman — APPROVED** [review]

**Review by derrell — APPROVED** [review]

**Review by oetiker — APPROVED** [review]

**Review by cboulanger — APPROVED** [review]

**Review by level420 — APPROVED** [review]

**Pull request merged**
