### PR TITLE
remove all grunt stuff

### PR DESCRIPTION
**Pull request by hkollmann**

### CODE REVIEW

**Comment by oetiker** [comment]
@hkollmann your patch breaks the testing system.

**Review by level420 — APPROVED** [review]

**Comment by level420** [comment]
Tested by creating a new app and generating build, source, test-source and test without problems. Additionally build the framework test in source and build version.

**Review by oetiker — APPROVED** [review]

**Review by cboulanger — APPROVED** [review]

**Comment by derrell** [comment]
The grunt stuff was added prior to the last release. Mightn't there be people depending on it? I don't object to removing it, but I suspect it should be only in a major release, and should await qxcompiler being included as an alternative to generate.py.

**Comment by johnspackman** [comment]
We're working on making qxcompiler the default in 6.0, I'm just readying server builds and then API generation and we're pretty much there for alpha testing ... (famous last words :) )

**Comment by hkollmann** [comment]
@derrell: The grunt stuff is only removed during creation of new projects. Old Projects are not touched.

**Review by derrell — APPROVED** [review]

**Comment by level420** [comment]
4 approvals, more than 2 business days, merged.
Thank you @hkollmann

**Pull request merged**
