### PR TITLE
Add ability to return a qx.Promise

### PR DESCRIPTION
**Pull request by voger**
This is a first attempt to make `qx.io.request.Xhr` to return a `qx.Promise`. 

On promise resolution it returns the xhr object as a parameter to then's callback. 

On rejection it throws a qx.type.BaseError with the phase as a comment. If the request fails with `statusError`, the `qx.type.BaseError` object has "error code: error message" as failMessage. If it fails for some other reason, e.g. `timeout` the `failMessage` is just an empty string.

### CODE REVIEW

**Comment by hkollmann** [comment]
Great!

Would it be possible to implement this method in qx.io.request.AbstractRequest? 
So qx.io.request.Jsonp would have the same benefit?

And could you suround the method with 

      if (qx.core.Environment.get("qx.promise")) {

Your method...

      } else {
        this.skip("Skipping because qx.promise==false");
      }

Because promise support can be disabled through enviroment setting.

Thanks for sharing code again!

**Comment by hkollmann** [comment]
Question to all: I like sendSync better than sendWithPromise. What do you think?

**Comment by zaucker** [comment]
sendP() is used other places.

Fritz Zaucker
Platanen 42
4600 Olten
+41 62 212 7712
+41 79 675 0630

**Comment by voger** [comment]
@hkollmann thanks for the feedback. I will try to implement it as AbstractRequest and I will surround it with the conditional.

I opted for the name `sendWithPromise` because `qx.io.request.Xhr` already has a property named `async` that controls "Whether the request should be executed asynchronously", and I believe it would be confusing as to what `sendAsync` refers to. 

Also, I would like some feedback as to what is would be best to be returned in each case. Right now it returns the xhr object on resolution and a qx.type.BaseError() with a string like "statusError: 404: Not found" on rejection. Are maybe there better options?

**Comment by cboulanger** [comment]
What about instead of adding a method, you create a new subclass `AsyncRequest` (since XHR is really old terminology), which doesn't have the `sendAsync` property and of which the `send` method returns a promise by default? You could put some of the common methods in a mixin or into the abstract class.

**Comment by voger** [comment]
@cboulanger In that case the `qx.io.request.Xhr` API would stay the same. It wouldn't have the ability to return a promise. Also `qx.io.request.Jsonp` wouldn't share the ability to return the promise either.  

Another idea I just got:

Right now the `qx.io.request.AbstractRequest#send` method doesn't return anything. What if I change it so it returns the promise? I know that it modifies working API but since nobody expected a return value from that method, how would it affect already working code?

**Comment by hkollmann** [comment]
Good idea. Should´nt be a breaking change. 

Von meinem iPad gesendet

**Comment by hkollmann** [comment]
Promise only if async is true!

**Comment by cboulanger** [comment]
@voger You're right, it makes more sense to add Promise support to all of the request types.

I like the Promise as return value but since it would create useless Promise objects to any code that works with events, maybe an extra property is in order, such as  a boolean `returnPromise`-property?

**Comment by voger** [comment]
@cboulanger yes indeed. It would create a useless object for someone who doesn't need it. 


I'm thinking that adding another check to the `send()` function would add another asterisk in it's use making it a bit more complicated  to reason about. It would return a promise if promises are enabled and if the property is set to true, otherwise it would return `undefined`(?). In case of synchronous communication it would return a settled promise. I am afraid all this would increase usage complexity for the `send()` function.

Maybe simply adding a method that returns a promise would be much simpler to use. What do you think?

**Comment by cboulanger** [comment]
@voger Probably you are right and the most straightforward approach is to leave `send()` as it is as a relic of the ancient Promises-less ways and just use a slightly more verbose method name to move into the future. 😄

**Review by cboulanger — DISMISSED** [review]

**Review by johnspackman — APPROVED** [review]

**Comment by voger** [comment]
@hkollmann I will move it to AbstractRequest but I will need few days so I can also asjust the tests properly.

**Review by johnspackman — DISMISSED** [review]

**Review by hkollmann — CHANGES_REQUESTED** [review]
Should be moved to AbstractRequest. 
@voger  will do this. So this should block merging up to that.

**Comment by oetiker** [comment]
I have added a label to make it clear that this one should not be merged yet

**Review by derrell — CHANGES_REQUESTED** [review]
I think this is being moved to the abstract class. Awaiting that change.

**Comment by voger** [comment]
Yes. I moved it already to the abstract class, added ability to reject the promise on abort it and I am adding a listener for `parserError`. I believe today or tomorrow I will push the updates.

**Review by hkollmann — APPROVED** [review]
That's it! Thanks @voger !

**Review by cboulanger — APPROVED** [review]

**Review by derrell — APPROVED** [review]

**Comment by voger** [comment]
Can we please postpone merging this? I think I found a bug. If the user attaches another `finally()` function in the chain, then the cleanup `finally()` code is not called. I am working on a fix for this.

**Review by hkollmann — CHANGES_REQUESTED** [review]
@voger founds a bug. Hold back to resolve this

**Comment by voger** [comment]
I rewrote this function so it desn't depend on a call to `finally()` for cleanup.

* Now every event listener performs the cleanup if it can settle the promise. 
* Also the event listener doesn't listen for separate error events anymore. We have a single listener for `changePhase`, and depending on the phase, it acts upon or ignores the event. This minimizes the number of event listeners that need to be registered/removed every time.
* `parseError` is handled as a special case because it is not a phase and can't be listened with `changePahse`

**Comment by cboulanger** [comment]
@voger once the tests pass, is this ready for merging?

**Comment by voger** [comment]
@cboulanger Yes. It is ready.

**Review by hkollmann — APPROVED** [review]

**Review by johnspackman — APPROVED** [review]

**Review by oetiker — APPROVED** [review]

**Comment by cboulanger** [comment]
Full quorum, merging. Thank you, @voger !

**Pull request merged**
