### PR TITLE
Allow to add async function as listeners

### PR DESCRIPTION
**Pull request by valette**
This is the clean version of the PR, with a lot of help from @oetiker and @level420 

This PR replaces #9225

### CODE REVIEW

**Comment by valette** [comment]
Note that in this PR, the test is very simple and does not cover as much as the test for 'normal' functions, as the spy() method used for testing listeners cannot be used anymore.

**Review by level420 — APPROVED** [review]

**Review by derrell — APPROVED** [review]
I am not yet too familiar with async functions, but I don't see anything in here that looks like it would cause problems.

**Review by oetiker — APPROVED** [review]

**Comment by level420** [comment]
more than 2 business days. 3 approvals.
merging.
thank you @valette

**Comment by valette** [comment]
Well, thank _you_ _all_ for maintaining Qooxdoo!

**Pull request merged**
