### PR TITLE
Fixes for unit tests

### PR DESCRIPTION
**Pull request by johnspackman**
fix: fixes a bug with classes with `null` extend not having its constructor assigned
fix: fixes a bug where anonymous inner classes could cause the outer class to be erased if the inner class is undefined
fix: fixes a bug in reading stack traces on chrome
fix: fixes unit tests

### CODE REVIEW

**Review by cboulanger — APPROVED** [review]
Wow, this must have been a lot of work. Thank you.

**Review by derrell — APPROVED** [review]

**Comment by johnspackman** [comment]
FWIW the theme based tests would benefit from review - they depend on specific values in the theme, but this is very fragile because the theme can be legitimately edited to something different, which unexpectedly breaks the tests.  Also, some of the tests are actually useful to run on each of the themes (eg Form tests need to test that the invalid appearances are applied).  I've started to make it theme-agnostic, but there's bits in there which will take more work to do properly.  So long as we stick with Simple theme for the moment it should be fine

**Comment by derrell** [comment]
How about including a complete theme in the test framework so that it is independent of the supplied themes that could legitimately be altered?

**Comment by johnspackman** [comment]
> How about including a complete theme in the test framework so that it is independent of the supplied themes that could legitimately be altered? 

Yes, that would be ideal - although actually you need two for some of the tests so that we can test for things like colour changes if you swap out just the decorators.  It's just that what we have not should be sufficient to pass tests, it's just an FYI that it needs some love in the future

**Review by hkollmann — APPROVED** [review]

**Review by oetiker — APPROVED** [review]

**Review by hkollmann — APPROVED** [review]

**Comment by hkollmann** [comment]
Now the generator tests do not work any longer?

**Comment by cboulanger** [comment]
I fear we cannot have both. We can give the travis tests the boot, since we know they worked before - and run compiler-based test from now on.

**Comment by cboulanger** [comment]
A different option would be to duplicate the code under `qx.test` namespace (with the changes in this PR) and place it as a Library (with a different namespace) in the `test` directory , and leave the Generator-based `qx.test` namespace as it is. This would allow to keep the Travis/Saucelab tests as they are.

**Review by level420 — APPROVED** [review]

**Pull request merged**
