### PR TITLE
first attempt at getting old builds back

### PR DESCRIPTION
**Pull request by oetiker**

### CODE REVIEW

**Review by derrell — DISMISSED** [review]
I don't know anything about this stuff, so I'll approve so I don't hold up the process.

**Review by cboulanger — DISMISSED** [review]
My knowledge of the testing workflow is almost zero, but I welcome any attempt to make it work again.

**Review by hkollmann — DISMISSED** [review]

**Review by johnspackman — DISMISSED** [review]

**Comment by hkollmann** [comment]
I think this needs a direct commit. During PR test should run… 
This is the cat biting it's tail

**Review by level420 — DISMISSED** [review]

**Review by johnspackman — APPROVED** [review]

**Review by cboulanger — APPROVED** [review]

**Review by level420 — APPROVED** [review]

**Review by derrell — APPROVED** [review]

**Comment by oetiker** [comment]
hmmm why does this beast no see that travis is happy ?

**Pull request merged**
