### PR TITLE
Format using the calendar year to support Buddhist (Thai) calendars.

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by level420** [comment]
@iceteagroup some travis tests are failing which seems related to your PR.
See https://travis-ci.org/qooxdoo/qooxdoo/jobs/265695230
and there for example:
```
Firefox 55.0.0 (Linux 0.0.0) qx.test.ui.form DateField:test: setting value sets date of chooser FAILED
	Exception while creating child control 'list' of widget qx.ui.form.DateField[12203-1]: this.__getCalendarYear is not a function
		qx.util.format.DateFormat:10824
```

You could simply add modifications to your PR by adding commits to the branch icedteagroup:patch-1 in your qooxdoo fork on github

**Comment by iceteagroup** [comment]
Ops, missing closing of the comment.

**Comment by oetiker** [comment]
@iceteagroup this PR is still failing to compile

**Review by patrick-fischer-hirschstein — APPROVED** [review]

**Comment by level420** [comment]
@iceteagroup the tests for this PR are failing. Please use the testrunner to identify what is wrong and adapt your PR or if necessary the tests accordingly. 
Here are the failing tests:
```
Firefox 55.0.0 (Linux 0.0.0) qx.test.util DateFormat:testDateParse FAILED
	Expected '-20' but found '2021'!
		qx.core.AssertionError.constructor:326
		qx.core.Assert.__fail:1179
		qx.core.Assert.assertEquals:4808
		qx.type.BaseString.assertEquals:779
		qx.test.util.DateFormat._testDateParse:7
		qx.test.util.DateFormat.testDateParse:9
		qx.dev.unit.TestFunction:1438
		qx.dev.unit.TestResult.run:5892
		qx.dev.unit.TestFunction.run:1287
		.runTest://localhost:9876node_modules/karma-qooxdoo/qooxdoo-adapter.js
...
Firefox 55.0.0 (Linux 0.0.0) qx.test.util DateFormat:testLocalizedDates FAILED
	Expected '-20' but found '2021'!
		qx.core.AssertionError.constructor:326
		qx.core.Assert.__fail:1179
		qx.core.Assert.assertEquals:4808
		qx.type.BaseString.assertEquals:779
		qx.test.util.DateFormat._testDateParse:7
		qx.test.util.DateFormat.testLocalizedDates:9
		qx.dev.unit.TestFunction:1438
		qx.dev.unit.TestResult.run:5892
		qx.dev.unit.TestFunction.run:1287
		.runTest://localhost:9876node_modules/karma-qooxdoo/qooxdoo-adapter.js
```

**Comment by level420** [comment]
@iceteagroup Could you please have a look into this PR again? Especially the failing tests `qx.test.util DateFormat:testDateParse` and `qx.test.util DateFormat:testLocalizedDates`? Thank you!

**Comment by iceteagroup** [comment]
Sorry, I thought I did. I will updated it today. Can I roll it back somehow? The code is now quite different on my end since the Thai calendar also needs parsing support.

**Comment by level420** [comment]
@iceteagroup the simplest way would be to create another PR and close this one.

**Pull request closed without merging**
