### PR TITLE
Let others know when we moved in q.u.c.MMovable.

### PR DESCRIPTION
**Pull request by jochumdev**
Signed-off-by: Rene Jochum rene@jochums.at

### CODE REVIEW

**Comment by cajus** [comment]
This will flood the event queue with many events that don't contain much more than the information that the mouse has moved. But not where, etc..

 So if someone wants to use it, he might need to add additional code to find out where. From a performance point of view, I'm not sure if it's good to do that additionally. What about just listening for pointermove in your own code?

**Comment by pcdummy** [comment]
Thanks for your input @cajus, i can't listen on pointermove as this does e.stopPropagation().
Before this i've overwritten onMovePointerMove and then called this.base(arguments, e). not sure whats better.

**Comment by cajus** [comment]
Did you try _caputure=true_ vs _capture=false_ in the listener?

**Comment by pcdummy** [comment]
Thank you @cajus, `capture=true` works for me which makes this PR obsolete.

**Comment by cajus** [comment]
Cool ;-)

**Pull request closed without merging**
