### PR TITLE
Replace misspelled method detatchPointerEvents in qx.ui.virtual.selection.Abstract

### PR DESCRIPTION
**Pull request by level420**
offer a correctly spelled detachPointerEvents method and deprecate the false spelled.

### CODE REVIEW

**Review by cboulanger — APPROVED** [review]

**Review by hkollmann — APPROVED** [review]

**Review by derrell — APPROVED** [review]
Approving this as a good fix, but aren't there in-qooxdoo use cases of the now-deprecated method? If so, they should be corrected to use the properly spelled, new method name, too, shouldn't they?

**Comment by level420** [comment]
@derrell I didn't find any other occurrence of detatchPointerEvents in the whole framework.

**Comment by derrell** [comment]
Ok, great. Thanks for checking.

**Review by oetiker — APPROVED** [review]

**Review by johnspackman — APPROVED** [review]

**Comment by level420** [comment]
merging. thank you for approving.

**Pull request merged**
