### PR TITLE
Add test for property selectable on Atom

### PR DESCRIPTION
**Pull request by zaucker**
Forward property selectable from Atom to it's label child control
Add test for setting/unsetting selectable property on Label
Fix typo in test name for Label

### CODE REVIEW

**Comment by level420** [comment]
@zaucker the travis tests fail exactly in you newly added tests.

**Comment by zaucker** [comment]
I guess my test must be wrong. Just don't see (yet) why ...

**Comment by level420** [comment]
maybe the dom is not ready yet, and does not reflect the attributes. You maybe have to flush the queues (just guessing)?

**Comment by zaucker** [comment]
Giving it a try ...

**Comment by level420** [comment]
Have a look into this test. I think there is no dom created until you add the label to the root and then flush it:
https://github.com/qooxdoo/qooxdoo/blob/master/framework/source/class/qx/test/bom/Font.js#L146

**Comment by zaucker** [comment]
@level420 Thanks, another try.

**Comment by level420** [comment]
and it should be ```.getContentElement().getDomElement().getAttribute('qxselectable')```
Tested this here locally in my app

**Comment by zaucker** [comment]
@level420 Thanks again, I guess testing locally would have been more efficient than going through Travis several times ...

**Comment by level420** [comment]
:ballot_box_with_check: CALL FOR VOTES

**Comment by zaucker** [comment]
Hmm, not sure if voting for my own PR is really appropriate ... :-)

**Comment by oetiker** [comment]
@zaucker your suspicion is correct you can not vote for your own PR as per our rules in https://github.com/qooxdoo/qooxdoo-wiki/blob/master/Developer-Documentation.md

**Comment by zaucker** [comment]
OK, I just unvoted ... :-)

**Comment by level420** [comment]
Five votes. Merging.
Thank you @zaucker

**Pull request merged**
