### PR TITLE
Added documentation for "externalResources"

### PR DESCRIPTION
**Pull request by mbgonicus**
as discussed in the qxcompiler gitter chat

### CODE REVIEW

**Comment by hkollmann** [comment]
This description is part of the "old" pyhton based toolchain. externalResources only works for new toolchain. This should be mentioned.

IMHO you should copy the whole description to the qooxdoo-cli repos:
https://github.com/qooxdoo/qooxdoo-cli/tree/master/docs as manifest.md.

OK, needs a conversion to md format, too.

**Comment by mbgonicus** [comment]
All right, added the information that it's only available for the new compiler. Also added the documentation for the cli repo: https://github.com/qooxdoo/qooxdoo-cli/pull/87

**Review by hkollmann — APPROVED** [review]

**Review by level420 — APPROVED** [review]

**Review by derrell — APPROVED** [review]

**Review by cboulanger — APPROVED** [review]

**Comment by cboulanger** [comment]
Thank you!

**Review by johnspackman — APPROVED** [review]

**Comment by hkollmann** [comment]
4 days, 5 approvals, merged.
Thanks @mbgonicus

**Pull request merged**
