### PR TITLE
This is just a test what happens if we change the package name

### PR DESCRIPTION
**Pull request by hkollmann**

### CODE REVIEW

**Review by derrell — COMMENTED** [review]
If it's just a test, do you really want it merged with master?

**Comment by cboulanger** [comment]
I think @johnspackman has a plan how to roll this out. At the moment, there are a lot of projects that rely on the `qooxdoo` package - I think we have to be careful...

**Comment by cboulanger** [comment]
Just saw your conversation on Gitter! It would be good to have the new setup, in particular having the qooxdoo-sdk package.

**Comment by hkollmann** [comment]
Not yet - i just want to see the travis results

**Comment by hkollmann** [comment]
qooxdoo package is qooxdoo server - generated during build process,. No plans to touch this package in the moment!
The package i think of is qooxdoo-sdk wich should contain the whole Framework.

**Comment by cboulanger** [comment]
We need an issue to remove grunt completely.

**Comment by hkollmann** [comment]
I once tried this. But the whole test enviroment of qooxdoo requires grunt.

**Comment by hkollmann** [comment]
Will come back with more explenation after tests are over

**Pull request closed without merging**
