### PR TITLE
Bump CLDR to 30.0.2 and extract 'latn' number formats

### PR DESCRIPTION
**Pull request by cajus**
There was a change in CLDR data that breaks the generator code for some languages: number formats are now optionally tagged by a *numberFormat*. If there are multiple definitions, the generator picks the first of them - which might result in *arabic* instead of *latin* number formats.

I used that commit to also bump the CLDR version (again).

### CODE REVIEW

**Comment by RemiHeugue** [comment]
It works :+1: (don't forget to run generate.py distclean)

I've got some warnings during the first run though:
```
  - Processing 3 locales  qooxdoo/tool/pylib/misc/cldr.py:138: FutureWarning: The behavior of this method will change in future versions. Use specific 'len(elem)' or 'elem is not None' test instead.
  if not decimalSeparatorNode:
qooxdoo/tool/pylib/misc/cldr.py:146: FutureWarning: The behavior of this method will change in future versions. Use specific 'len(elem)' or 'elem is not None' test instead.
  if not groupSeparatorNode:
qooxdoo/tool/pylib/misc/cldr.py:152: FutureWarning: The behavior of this method will change in future versions. Use specific 'len(elem)' or 'elem is not None' test instead.
  if not percentFormatNode:
```

**Comment by cajus** [comment]
So we've different python versions. Mine does not note anything - but it's easy to fix.

**Review by level420 — APPROVED** [review]

**Comment by level420** [comment]
I trust in @cajus :-)

**Comment by cajus** [comment]
@level420 I've expected you to check every single line of CLDR change ;-)

**Comment by cajus** [comment]
The caveat of that solution is that we only support latin number formats. But changing stuff to support multiple of them isn't quite straight forward. I'd wait for a bug report that want's arabic number formats in frech, though ;-)

**Review by johnspackman — APPROVED** [review]

**Review by oetiker — APPROVED** [review]

**Review by derrell — APPROVED** [review]

**Review by zaucker — APPROVED** [review]

**Comment by level420** [comment]
Full quorum. Merging.
Thank you @cajus

**Pull request merged**
