### PR TITLE
Fixing issue #9599 - width/height mixup in high-res images

### PR DESCRIPTION
**Pull request by jpriebe**
does just what the subject line says.  :-)

### CODE REVIEW

**Review by derrell — DISMISSED** [review]
My only concern here is that this _should_ have been commonly-used code, so why was it never discovered before? Are we missing something insidious?

**Comment by johnspackman** [comment]
@derrell i would guess that 2DP images are rarer, and that they're normally used for icons so they're normally square

**Review by johnspackman — DISMISSED** [review]

**Review by hkollmann — DISMISSED** [review]

**Review by cboulanger — DISMISSED** [review]

**Review by level420 — DISMISSED** [review]

**Comment by jpriebe** [comment]
Sorry, guys.  I just screwed this up by pushing another set of changes for a related issue (tables don't support high-res images).  Let me try to clean up the mess.

**Comment by jpriebe** [comment]
OK, I rebased the 2nd commit out of the branch.

**Review by cajus — APPROVED** [review]

**Review by johnspackman — APPROVED** [review]

**Review by oetiker — APPROVED** [review]

**Review by cboulanger — APPROVED** [review]

**Review by hkollmann — APPROVED** [review]

**Pull request merged**
