### PR TITLE
Use 'Indigo' theme as the default theme for new apps

### PR DESCRIPTION
**Pull request by woprandi**

### CODE REVIEW

**Comment by oetiker** [comment]
that's just the default themes for the templates, right ? what about the api viewer, the demo browser and the other sample apps ?

**Comment by woprandi** [comment]
only tutorials have old theme. I can update them also

**Comment by oetiker** [comment]
If we do it, I think it should be consistant

**Comment by woprandi** [comment]
Yeah, but we should also update tutorial screenshots

**Comment by woprandi** [comment]
Updated PR

**Comment by oetiker** [comment]
the apps don't need any changes ?

**Comment by woprandi** [comment]
Apps already use the indigo theme

http://demo.qooxdoo.org/current/showcase
http://demo.qooxdoo.org/current/widgetbrowser/
http://demo.qooxdoo.org/current/feedreader/
http://demo.qooxdoo.org/current/demobrowser/
...

**Comment by oetiker** [comment]
ok ... in that case I merge

**Pull request merged**
