### PR TITLE
DateChooser with min and max values

### PR DESCRIPTION
**Pull request by goldim**
The standard `input="date"` html element does have _min_ and _max_ attributes which restrict user from setting "invalid" dates. DateChooser and DateField (which contains DateChooser as a child) don't support this functionality. I decided add it via properties _MinValue_ and _MaxValue_. If MinValue is set then dates less _MinValue_ are not pickable and the same about _MaxValue_. If code I added not efficient let me know. I will fix it.

### CODE REVIEW

**Review by derrell — CHANGES_REQUESTED** [review]
This looks good, code-wise. Please add doc strings to the two new properties so that they show up in the API viewer.

**Review by cboulanger — APPROVED** [review]
Cool, thanks!

**Review by johnspackman — APPROVED** [review]

**Review by oetiker — APPROVED** [review]

**Comment by goldim** [comment]
@derrell Hello, thanks for response, I did. About props I don't sure is it worth to add event? how usefull will it be? For my goals it was needed. I think if somebody wants to have them it's not difficult to add them anytime.

**Review by derrell — APPROVED** [review]

**Review by level420 — APPROVED** [review]

**Review by hkollmann — CHANGES_REQUESTED** [review]
immediately after the `=>` (arrow-body-style) at source/class/qx/test/core/Property.js:1066:43:
81
  1064 | 
82
  1065 |     testPromises() {
83
> 1066 |       const promiseDelay = (delay, fn) => {
84
       |                                           ^
85
  1067 |         return new qx.Promise(resolve => {
86
  1068 |           setTimeout(async () => {
87
  1069 |             await fn();
88



Could you fix the lint error first and have a look at the not running datechooser tests

Thanks,
Hennrt

**Comment by hkollmann** [comment]
Could you run `npm test` in your local copy and check if this test failures are github speficic?

**Comment by goldim** [comment]
@hkollmann okay, will do it, thx.

**Comment by goldim** [comment]
@hkollmann I checked local tests and errors the same. The errors with DataChooser were before my changes. I can fix some tests but have I to create separate PR or commit to this one?

**Comment by hkollmann** [comment]
Commit to this one

**Comment by goldim** [comment]
@hkollmann I decresed amount of failed tests. All failed tests are not related with my changes of this PR. About some failed tests I created  issues and fixed lint error.

**Review by hkollmann — APPROVED** [review]

**Pull request merged**
