### PR TITLE
Adds to the meta data to say whether a method is async or not

### PR DESCRIPTION
**Pull request by johnspackman**
This allows the API viewer to flag up whether a method is asynchronous or not

### CODE REVIEW

**Review by hkollmann — APPROVED** [review]

**Comment by goldim** [comment]
@johnspackman btw my last PR was with static methods in API viewer and there static meta is checked against isStatic and meta didn't include this prop. I fixed it in API viewer but after I saw u did it in qooxdoo framework I think this fix also could be done. Am I right?

**Comment by johnspackman** [comment]
@goldim sorry I didnt see your PR in API viewer - what you've done looks fine, do you mean you want to show whether a function is async or not in the search results?  The `isAsync()` method should work for static and normal methods

**Review by oetiker — APPROVED** [review]

**Comment by goldim** [comment]
@johnspackman I wanted to show static methods but meta of static method lacks of isStatic. I added isStatic in meta in API viewer code but thinks it was a bad solution. It is like with isAsync.

**Comment by goldim** [comment]
Abstract class - isAbstract and signleton - isSingleton. It is up to you, I just suggested.

**Review by derrell — APPROVED** [review]

**Review by goldim — APPROVED** [review]

**Review by cboulanger — APPROVED** [review]

**Pull request merged**
