### PR TITLE
add manual entry on using external JS libs

### PR DESCRIPTION
**Pull request by thron7**
This is just a doc PR, but since I answered this question a couple of times (recently [here](http://stackoverflow.com/a/39555502/127465)) I thought it was worth a manual entry.

Caveat: The section about wrapping an external lib in a qooxdoo class is incomplete. I've looked through some of Tobi's contributions, but they are quite elaborate especially when loading is concerned, and they also rely on older qooxdoo versions (at least in parts). Maybe he can come up with an updated, simplified version which only shows the bare minimum you need to do, and  fill in the missing pieces.

### CODE REVIEW

**Comment by oetiker** [comment]
cool will work through ... this ...

**Comment by oetiker** [comment]
I think we should get @level420 s script loader mixin mentioned too

**Comment by oetiker** [comment]
hi @thron7

now that the dynamic script loader is merged, could you update your documentation patch ?

**Comment by thron7** [comment]
I can do that but would need some input from you guys, as I'm not acquainted with the DynamicScriptLoader. Is there still a usage example in the class comment?

As for this PR, I'm surprised it is not already merged so I could do a new patch :-) . Seriously, is there any reason to not merge incremental improvements? This PR is already sooo old ... 

But if you wish I can try and enhance it. Can I just add new commits, or do I have to re-merge master before that?

**Comment by oetiker** [comment]
ok lets merge it

**Review by oetiker — APPROVED** [review]

**Review by level420 — APPROVED** [review]

**Comment by level420** [comment]
documentation only PR. 2 approvals.
merging
Thank you @thron7

**Pull request merged**
