### PR TITLE
Issue #9182 Detect unified pointer input model for Chrome >= 55

### PR DESCRIPTION
**Pull request by level420**
Fixes issue #9182

### CODE REVIEW

**Review by oetiker — APPROVED** [review]

**Review by cajus — APPROVED** [review]

**Review by zaucker — APPROVED** [review]

**Review by johnspackman — APPROVED** [review]

**Comment by level420** [comment]
@derrell This PR uses ```window.PointerEnabled``` [1] to test for the unified pointer event model in chrome >= version 55 which is different from the deprecated ```Navigator.pointerEnabled``` [2] api.

Note that ```Navigator.pointerEnabled``` was just introduced in chrome 54 in order to " ... only estimate its usage" (see [2]).

[1] https://developers.google.com/web/updates/2016/10/pointer-events#browser_support
[2] https://groups.google.com/a/chromium.org/forum/#!msg/chromium-reviews/K9BP8KJXCbc/OlzpwJuqEAAJ

**Review by derrell — APPROVED** [review]

**Comment by cajus** [comment]
5 approvals. Giving it a shot. Thanks @level420

**Comment by pRiVi** [comment]
... you realy should make a new release on https://github.com/qooxdoo/qooxdoo/releases

**Comment by schlagges** [comment]
+1 for a Release. See https://github.com/qooxdoo/qooxdoo/pull/9182

**Comment by websoft** [comment]
+1 for a Release

**Pull request merged**
