### PR TITLE
change map to ol3

### PR DESCRIPTION
**Pull request by hkollmann**
change the map example to the modern ol3 classes

### CODE REVIEW

**Comment by oetiker** [comment]
thanks for your contributions

**Comment by level420** [comment]
Didn't check that, but do we have tests for the openlayer integration?

**Comment by oetiker** [comment]
note this is part of the showcase .... not part of the library

**Comment by cajus** [comment]
@level420 I don't think that there are tests for the demos at all.

**Comment by level420** [comment]
Ah! Now I understand! Thank you all

**Comment by cajus** [comment]
Just gave it a try. Seems to work fine. Thanks ;-)

**Comment by level420** [comment]
3 thumbs up and more than 2 business days.
merging.
Thany you @hkollmann

**Pull request merged**
