### PR TITLE
fixes deployment

### PR DESCRIPTION
**Pull request by johnspackman**

### CODE REVIEW

**Comment by cboulanger** [comment]
I am confused `-f` seems to be the parameter name for "feedback" (https://github.com/qooxdoo/qooxdoo-compiler/blob/master/source/class/qx/tool/cli/commands/Compile.js#L115-L119), I thought `-c`/`--configFile` was the parameter name, but I don't see it in there ...

**Review by hkollmann — APPROVED** [review]

**Comment by johnspackman** [comment]
@cboulanger you're right, hang on

**Comment by cboulanger** [comment]
Where is the parameter name for the config file specified? `-c` is for clean, so it's not that. The Yargs docs still contain the old form (https://github.com/qooxdoo/qooxdoo-compiler/blob/master/source/class/qx/tool/cli/commands/Compile.js#L158)

**Comment by johnspackman** [comment]
it's in https://github.com/qooxdoo/qooxdoo-compiler/blob/master/source/class/qx/tool/cli/Cli.js#L91-L94

**Comment by johnspackman** [comment]
i'll fix the conflict with `-c` in the compiler tomorrow, but this should fix the deployment

**Review by cboulanger — APPROVED** [review]

**Pull request merged**
