### PR TITLE
change qx.lang.normalize.Array shims to not be enumerable

### PR DESCRIPTION
**Pull request by johnspackman**
As reported here https://github.com/qooxdoo/qooxdoo/issues/9176

### CODE REVIEW

**Review by derrell — APPROVED** [review]
LGTM

**Review by level420 — APPROVED** [review]

**Review by oetiker — APPROVED** [review]

**Review by oetiker — CHANGES_REQUESTED** [review]
please change the color of the semicolon

**Review by oetiker — APPROVED** [review]

**Review by derrell — CHANGES_REQUESTED** [review]
Please make some minimal change so we can test the Request Changes feature.

**Review by derrell — APPROVED** [review]
This whitespace change makes all the difference. Approved!

**Comment by level420** [comment]
:ballot_box_with_check: CALL FOR VOTE

**Review by oetiker — APPROVED** [review]

**Review by cajus — APPROVED** [review]

**Comment by level420** [comment]
More than two business days. 4 approvals.
Merging.
Thank you @johnspackman

**Pull request merged**
