### PR TITLE
Transform property

### PR DESCRIPTION
**Pull request by johnspackman**
This PR extends the property definition so that the `transform` method also receives the value currently assigned to the property (or undefined) as well as the new value.

This makes `transform` analogous to the `apply` method, and provides information which is not otherwise available; note that it is not ideal to call the property’s `getXxx` method because this can throw exceptions if the property has not yet been initialised, and adding try/catch handlers complicates property implementation unnecessarily (especially when the property system has the existing value to hand)

This is a non-breaking change.

### CODE REVIEW

**Comment by level420** [comment]
@johnspackman Is the ability to declare a transform method new to this release?

**Comment by derrell** [comment]
I added transforms about 10 years ago.

**Comment by level420** [comment]
Oh no! It was already there. Never used it.

**Review by level420 — CHANGES_REQUESTED** [review]
I think the documentation should also be changed accordingly:

here: https://github.com/qooxdoo/qooxdoo/blob/master/framework/source/class/qx/core/Property.js#L85-L93

and here: https://github.com/qooxdoo/qooxdoo/blob/master/documentation/manual/source/pages/core/defining_properties.rst

**Comment by johnspackman** [comment]
@level420 all done

**Review by level420 — APPROVED** [review]

**Comment by level420** [comment]
Thank you @johnspackman !

**Review by zaucker — APPROVED** [review]

**Review by derrell — APPROVED** [review]

**Review by oetiker — APPROVED** [review]

**Review by cajus — APPROVED** [review]

**Review by zaucker — APPROVED** [review]

**Comment by level420** [comment]
Full quorum. Merging.
Thank you @johnspackman

**Pull request merged**
