### PR TITLE
Avoid usage of qx.bom.Selector by replacing it with native document.getElementsByTagName

### PR DESCRIPTION
**Pull request by level420**
This avoids gui dependencies in non gui runtime environments

### CODE REVIEW

**Comment by level420** [comment]
@ronkie could you please check if this solution works for you? Thank you!

**Review by derrell — APPROVED** [review]
This simple solution seems to solve the problem of load-time browser assumptions in server-side code.

**Review by ronkie — APPROVED** [review]
I think this should work fine for the initial problem.

**Review by cboulanger — APPROVED** [review]

**Review by cajus — APPROVED** [review]

**Review by johnspackman — APPROVED** [review]

**Comment by johnspackman** [comment]
5 approvals, 8 days - merging, thanks @level420 !

**Pull request merged**
