### PR TITLE
fixes tutorial - it should not be necessary to specify the framework,…

### PR DESCRIPTION
**Pull request by johnspackman**
… but doing so will break under current qxcompiler

### CODE REVIEW

**Review by cboulanger — APPROVED** [review]

**Review by hkollmann — APPROVED** [review]
Framework is part of the compiler!

**Comment by johnspackman** [comment]
@hkollmann yes, but adding it in to the application as a dependency should not break the app.  IMHO its a bug https://github.com/qooxdoo/qooxdoo-compiler/issues/474

**Review by oetiker — APPROVED** [review]

**Comment by cboulanger** [comment]
this circular dependency is bad. The compiler obviously must hava a dependency on the framework, but isn't the reverse only true as one of the "devDependencies"? I.e. the framework works with the python toolchain in default (until v.7) and the compiler is currently, even if we all treat it as the default toolchain, an add-on from the perspective of backwards-compatibility. It is needed to compile the NPM package only. So it could be moved to "devDependencies" Or am I wrong?

Everything will be much better once we merge the two repos.

**Comment by hkollmann** [comment]
I am on the way to delete this reference in qooxdoo. I have more problems during building with this as it benefits.
In the Moment i am testing the build with my fork - will make a PR if everything works.

Testing in fork is much easier because it works without approval chain

**Comment by cboulanger** [comment]
Merging, thank you @johnspackman !
Sometimes it is necessary to add a random tag just to send an event to pullaprove to update the status.

**Pull request merged**
