### PR TITLE
[BUG #9135] '+' is allowed in an email address

### PR DESCRIPTION
**Pull request by woprandi**
This PR for the bug : http://bugs.qooxdoo.org/show_bug.cgi?id=9135

### CODE REVIEW

**Comment by wittemann** [comment]
Thanks for that. It would be great it would have a unit test to verify the change. This could be added here: https://github.com/qooxdoo/qooxdoo/blob/master/framework/source/class/qx/test/util/Validate.js#L43

**Comment by woprandi** [comment]
Yes, I will add a test in a new commit

**Comment by wittemann** [comment]
Great, this will get the PR in quickly.

**Comment by woprandi** [comment]
Added : https://github.com/woprandi/qooxdoo/commit/a98c56f352ca2f1825a9f621c9a538a56ed4b67c

**Comment by wittemann** [comment]
Thanks. :)

**Pull request merged**
