### PR TITLE
Fix qx.test.core.Property test

### PR DESCRIPTION
**Pull request by cboulanger**
class config maps must be separately defined to not produce compiler errors

### CODE REVIEW

**Review by hkollmann — APPROVED** [review]

**Review by level420 — APPROVED** [review]

**Review by johnspackman — APPROVED** [review]

**Review by derrell — CHANGES_REQUESTED** [review]
I don't see anything wrong with what was there before. If it was causing a compiler error, doesn't that indicate a problem with the compiler, rather than with this code? We should allow what this code was originally doing. That paradigm is used extensively in demobrowser and playground apps.

**Comment by cboulanger** [comment]
I'd say the test code is to assert a *run-time* behavior of the qooxdoo class system whereas the error thrown by the is a *compile-time* test, which correctly diagnoses a wrong class declaration in the code. I cannot think of a way how the compiler should know that the wrong declaration is purposely wrong. So in my view, it is not a bug of the compiler and declaring the config separately is the right response to the issue.

**Review by derrell — APPROVED** [review]
Understood. I see now what's going on there. (Is this a new test? If not, why did it not fail previously?)
Approving as is, but I am curious.

**Comment by cboulanger** [comment]
So far, we've run the framework tests with the generator only. If you run them with the compiler and the TestTapper test runner, you get different errors such as this one.

**Comment by derrell** [comment]
Ah, makes perfect sense. Thanks.

**Review by oetiker — APPROVED** [review]

**Pull request merged**
