### PR TITLE
[BUG #8952] FSM does not handle constant TERMINATE

### PR DESCRIPTION
**Pull request by mbgonicus**
fixes http://bugs.qooxdoo.org/show_bug.cgi?id=8952

For that purpose I added the private flag _terminated and for convenience the public function isTerminated().

### CODE REVIEW

**Comment by mbgonicus** [comment]
[BUG #8953] terminate event for FSM

I added this feature, but it requires the first fix (for #8952), so it is inside this PR.

**Comment by mbgonicus** [comment]
check. Sorry, didn't see it

**Comment by mbgonicus** [comment]
As far as the convention goes, no problem. I'll change that in the next commit.

I get your point to automatically restart the fsm and not fatal error the fsm. On the other hand that means one can use the fsm, although it is terminated. I don't know if that's expected behaviour. I expect a terminated fsm to not run unless the user starts it.

I think, that's a decision you must make. However, the result must be documented, so a user knows what to expect.

**Comment by derrell** [comment]
See my line note regarding line 745 in https://github.com/mbgonicus/qooxdoo/commit/820477fa2bc5ac11ac69eb71f43e79dac2ef4c74

**Comment by mbgonicus** [comment]
Ok, changed __terminated to __bTerminated and changed the fatal error to a debug message. Latest commit is 2b20d5a, see also https://github.com/qooxdoo/qooxdoo/pull/122/files

I'm sorry, but I cannot provide you with unit tests - workload to high.

**Pull request merged**
