### PR TITLE
Reset global cursor after a window closes

### PR DESCRIPTION
**Pull request by joskar**
This is a fix for an old bug see second issue of this [bug](https://github.com/qooxdoo/qooxdoo/issues/8936). Demonstration of the bug in the playground [here](http://tinyurl.com/zekfy25).

### CODE REVIEW

**Comment by level420** [comment]
@JosKar Reopened https://github.com/qooxdoo/qooxdoo/issues/8936

**Comment by zaucker** [comment]
@JosKar: what if another window has also changed the cursor to some other cursor? Then your fix would probably not have the desired effect.
I am not saying that the current behaviour is correct. But your fix might break other applications rather unexpectedly.

**Comment by cajus** [comment]
What to do with this one? If I understand the comments correctly, it fixes some bad behaviour, but is not general enough to be accepted just now? Is it generic fixable at all?

**Comment by johnspackman** [comment]
the bug is because the popup has been disposed of, but the layout is trying to position it's contentElement (and there is no element any more because it's been disposed).  I don't know why the proposed patch is fixing this, maybe it's by just changing the timing slightly (ie the lack of exception is a side effect rather than actually solving the problem).

This does not happen on Chrome 54 (dev channel) but does on FF 49.0.2.

I suspect that the correct fix is to resolve why the popup is being disposed before it is removed from the widget layout queue, rather than just change the cursor which as @zaucker says could have unintended side effects.  IMHO it requires more investigation before applying this fix.

**Comment by level420** [comment]
After studying the code in https://github.com/qooxdoo/qooxdoo/blob/master/framework/source/class/qx/ui/core/MResizable.js a bit, I came to the conclusion that this PR is totally valid, regarding the error with the cursor (as @JosKar wrote).

This is not a fix for the complete issue https://github.com/qooxdoo/qooxdoo/issues/8936 , only for the part with the cursor staying in resize mode when ESC is typed during resize.

Resetting the global cursor via ```this.getApplicationRoot().resetGlobalCursor();``` is valid, as it's done in the same way as it#s done if resizing is released or if the pointer is moved outside the resize frame/area: 
https://github.com/qooxdoo/qooxdoo/blob/master/framework/source/class/qx/ui/core/MResizable.js#L598-L605.

One addition though: I'd take the code from the sequence above and change that part in the destruct method to
```javascript
    if(this.getCursor()) {
      this.getApplicationRoot().resetGlobalCursor();
    }
```
which only resets the global cursor if we changed it.

**Comment by level420** [comment]
Start voting

**Comment by oetiker** [comment]
ok makes sense now

**Review by oetiker — APPROVED** [review]

**Review by cajus — APPROVED** [review]

**Review by zaucker — APPROVED** [review]

**Review by level420 — APPROVED** [review]

**Review by johnspackman — APPROVED** [review]

**Review by derrell — APPROVED** [review]

**Comment by level420** [comment]
Unbelievable!  A full quorum of 6 approvals!
Merging. Thank you @JosKar

**Pull request merged**
