### PR TITLE
Update AbstractImage.js

### PR DESCRIPTION
**Pull request by slachtar**
When changing table row height, images are aligned to top which  results on an ugly look, aligning it to middle fixes it.

### CODE REVIEW

**Review by oetiker — APPROVED** [review]

**Review by cboulanger — APPROVED** [review]
I am trying to think of cases where this might be a backward-compatibility issue. But probably there aren't such cases. It certainly is a better default behavior.

**Comment by hkollmann** [comment]
@slachtar: Could you write a comment here https://github.com/qooxdoo/qooxdoo/issues/9909 because it's not backward-compatibility.
So we should mention it in the release news.

**Review by level420 — APPROVED** [review]

**Review by derrell — APPROVED** [review]
This looks like it will be a visual BC difference for every application that that uses the image cellrenderer. This is the right time to make this change, as we come up on a major version bump, but it definitely needs to be in the release notes.

**Review by hkollmann — APPROVED** [review]

**Comment by slachtar** [comment]
> @slachtar: Could you write a comment here #9909 because it's not backward-compatibility.
> So we should mention it in the release news.

Sorry, was in vacation and noticied you already added the comments, thank you for accepting the PR.

**Pull request merged**
