### PR TITLE
Fixes #10713 - Progressive failures with multiple instances of row renderer

### LINKED ISSUE #10713: Progressive table renderer fails with multiple instances
If a single Progressive table uses multiple instances of `qx.ui.progressive.renderer.table.Row`, the subsequent instances do not render correctly.

**To Reproduce**
Run this in the playground:
```
  let createRow = function (rowNum, text) {
    let ret = {
      renderer: rowNum % 2 === 0 ? "small" : "tall",
      location: "end",
      data: [rowNum + "", text],
    };

    return ret;
  };

  let columnWidths = new qx.ui.progressive.renderer.table.Widths(2);
  columnWidths.setWidth(0, 60);
  columnWidths.setWidth(1, "1*");

  let columnNames = ["Row", "Text"];

  // Instantiate a Progressive with a structure including header
  let header = new qx.ui.progressive.headfoot.TableHeading(
    columnWidths,
    columnNames
  );
  let structure = new qx.ui.progressive.structure.Default(header);
  let p = new qx.ui.progressive.Progressive(structure);

  // Instantiate a data model and populate it.
  let dataModel = new qx.ui.progressive.model.Default();
  let rowData = [];

  rowData.push(createRow(0, "I am small."));
  rowData.push(createRow(1, "I am tall."));
  rowData.push(createRow(2, "This, too, is small."));
  rowData.push(createRow(3, "This, too, is tall."));

  dataModel.addElements(rowData);

  // Tell Progressive about its data model
  p.setDataModel(dataModel);

  // Instantiate a table row renderer
  let rowRenderer = new qx.ui.progressive.renderer.table.Row(
    columnWidths
  );

  // Give Progressive the renderer, and assign a name
  p.addRenderer("small", rowRenderer);

  // Instantiate another table row renderer for tall rows
  rowRenderer = new qx.ui.progressive.renderer.table.Row(
    columnWidths
  );

  // Set its default row height to be larger than the normal one
  rowRenderer.set(
    {
       defaultRowHeight: 40
    });

  // Give Progressive the renderer, and assign a name
  p.addRenderer("tall", rowRenderer);

  p.set({
    width: 400,
    maxWidth: 400,
  });

  this.getRoot().add(p, { left: 50, top: 50, bottom: 50 });

  p.render();
```

**Expected behavior**
1. The styles and columns are maintained on the rows using the second row renderer
2. Row colors are per-row-renderer-instance, as desired most of the time, but in the case of multiple instances of the same row renderer, we need a way to use more global color alternation.

### PR DESCRIPTION
**Pull request by derrell**
The wrong stylesheet was being selected for other than the first row renderer, yielding misplaced column data and incorrect styles produce by a subsequent row renderer.

Additionally, there was no provision for using a "global" (per all row renderers) background color scheme, so row color did not alternate properly. 

Added property `alternateBgColorsAllInstances` which defaults to `false` for BC behavior. When `true` in each row renderer instance, background colors alternate based on a class-static toggled boolean rather than instance-specific.

To see the new version work, create a new qooxdoo application (after applying this PR), with the following code in Application.js:

```
qx.Class.define("multipleRowRenderers.Application",
{
  extend : qx.application.Standalone,

  members :
  {
    main()
    {
      super.main();

      let createRow = function (rowNum, text) {
        let ret = {
          renderer: rowNum % 2 === 0 ? "small" : "tall",
          location: "end",
          data: [rowNum + "", text],
        };

        return ret;
      };

      let columnWidths = new qx.ui.progressive.renderer.table.Widths(2);
      columnWidths.setWidth(0, 60);
      columnWidths.setWidth(1, "1*");

      let columnNames = ["Row", "Text"];

      // Instantiate a Progressive with a structure including header
      let header = new qx.ui.progressive.headfoot.TableHeading(
        columnWidths,
        columnNames
      );
      let structure = new qx.ui.progressive.structure.Default(header);
      let p = new qx.ui.progressive.Progressive(structure);

      // Instantiate a data model and populate it.
      let dataModel = new qx.ui.progressive.model.Default();
      let rowData = [];

      rowData.push(createRow(0, "I am small."));
      rowData.push(createRow(1, "I am tall."));
      rowData.push(createRow(2, "This, too, is small."));
      rowData.push(createRow(3, "This, too, is tall."));

      dataModel.addElements(rowData);

      // Tell Progressive about its data model
      p.setDataModel(dataModel);

      // Instantiate a table row renderer
      let rowRenderer = new qx.ui.progressive.renderer.table.Row(
        columnWidths
      );
      rowRenderer.set(
        {
          alternateBgColorsAllInstances : true
        });

      // Give Progressive the renderer, and assign a name
      p.addRenderer("small", rowRenderer);

      // Instantiate another table row renderer for tall rows
      rowRenderer = new qx.ui.progressive.renderer.table.Row(
        columnWidths
      );

      // Set its default row height to be larger than the normal one
      rowRenderer.set(
        {
          alternateBgColorsAllInstances: true,
          defaultRowHeight: 40
        });

      // Give Progressive the renderer, and assign a name
      p.addRenderer("tall", rowRenderer);

      p.set({
        width: 400,
        maxWidth: 400,
      });

      this.getRoot().add(p, { left: 50, top: 50, bottom: 50 });

      p.render();
    }
  }
});
```

### CODE REVIEW

**Comment by derrell** [comment]
I've added label "Do not merge". I think there's a more general way to do the background row colors. I think as implemented, you couldn't have multiple tables with independent alternating row colors. I'll do some more work on this and then remove the "Do not merge" label.

**Comment by derrell** [comment]
Updated code. It now uses Progressive state's user data to store table-wide background color data. Here's an updated test Application.js:

```
qx.Class.define("multipleRowRenderers.Application",
{
  extend : qx.application.Standalone,

  members :
  {
    main()
    {
      super.main();

      let createRow = function (rowNum, text) {
        let ret = {
          renderer: rowNum % 2 === 0 ? "small" : "tall",
          location: "end",
          data: [rowNum + "", text],
        };

        return ret;
      };

      let columnWidths = new qx.ui.progressive.renderer.table.Widths(2);
      columnWidths.setWidth(0, 60);
      columnWidths.setWidth(1, "1*");

      let columnNames = ["Row", "Text"];

      // Instantiate a Progressive with a structure including header
      let header = new qx.ui.progressive.headfoot.TableHeading(
        columnWidths,
        columnNames
      );
      let structure = new qx.ui.progressive.structure.Default(header);
      let p = new qx.ui.progressive.Progressive(structure);

      // Instantiate a data model and populate it.
      let dataModel = new qx.ui.progressive.model.Default();
      let rowData = [];

      rowData.push(createRow(0, "I am small."));
      rowData.push(createRow(1, "I am tall."));
      rowData.push(createRow(2, "This, too, is small."));
      rowData.push(createRow(3, "This, too, is tall."));

      dataModel.addElements(rowData);

      // Tell Progressive about its data model
      p.setDataModel(dataModel);

      // Instantiate a table row renderer
      let rowRenderer = new qx.ui.progressive.renderer.table.Row(
        columnWidths
      );
      rowRenderer.set(
        {
          alternateBgColorsTableGlobal : true
        });

      // Give Progressive the renderer, and assign a name
      p.addRenderer("small", rowRenderer);

      // Instantiate another table row renderer for tall rows
      rowRenderer = new qx.ui.progressive.renderer.table.Row(
        columnWidths
      );

      // Set its default row height to be larger than the normal one
      rowRenderer.set(
        {
          alternateBgColorsTableGlobal: true,
          defaultRowHeight: 40
        });

      // Give Progressive the renderer, and assign a name
      p.addRenderer("tall", rowRenderer);

      p.set({
        width: 400,
        maxWidth: 400,
      });

      this.getRoot().add(p, { left: 50, top: 50, bottom: 50 });

      p.render();
    }
  }
});
```

**Comment by derrell** [comment]
Now ready for review.

**Review by goldim — APPROVED** [review]
Great! Works fine.

**Comment by hkollmann** [comment]
Could you add your test application into a new app in ```test/framework/app``` please?

**Comment by derrell** [comment]
> Could you add your test application into a new app in `test/framework/app` please?

Done.

**Review by hkollmann — APPROVED** [review]

**Review by cboulanger — APPROVED** [review]

**Review by oetiker — APPROVED** [review]

**Review by johnspackman — APPROVED** [review]

**Pull request merged**
