### PR TITLE
https://github.com/qooxdoo/qooxdoo/issues/10029: 404 errors for Mater…

### PR DESCRIPTION
**Pull request by hkollmann**
…ialIcons

add icons to Manifest.json re issue #10029

### CODE REVIEW

**Review by cboulanger — APPROVED** [review]

**Comment by oetiker** [comment]
note that this is only 'half' the rent ... actually it will make things worse at first ... since this will cause the compiler to generate code that tries to load these fonts, even when they do not exist ... see https://github.com/qooxdoo/qooxdoo-compiler/issues/760

**Comment by hkollmann** [comment]
MaterialIcons are part of qooxdoo resources - so they should be there

**Review by derrell — APPROVED** [review]

**Comment by oetiker** [comment]
@cboulanger when working with a checked out version of qdooxoo, then `framework/Manifest.json` is used while the packaged version uses `Manifest.json` this is also at the root of this problem ... maybe it would make sense to not have virtually the same file twice in the source treen?

**Comment by cboulanger** [comment]
@oetiker You probably meant to mention @hkollmann - I agree, but wonder if we should just keep it for now (except when there is a really simple and BC fix). Maybe we should move the whole source tree up one level in v7 and get rid of the "framework" folder entirely. We need to clean up the source tree anyways - so much stuff we can get rid of in v7.

**Comment by hkollmann** [comment]
The Manifest.json in framework contains stuff use by the python tolchain. With v7 we should cleanup

**Review by oetiker — APPROVED** [review]

**Comment by oetiker** [comment]
but to stress it again, merging this PR will make matters worse unless there is some sort of fix to the compiler, since now the code in the browser will try to load the material icon fonts despite the font files not being present as they would have to be copied using appropriate @asset lines ... which will only happen when you put these into your code or load the tangible theme ... 

without them the resulting code produced by the compiler will cause the error message this is said to prevent ... 

the error at the moment only shows in the git version of qooxdoo since the git version uses the Manifest.json in framework which already contains these lines ... while the packaged version of qooxdoo places the toplevel Manifest.json into framework and the toplevel Manifest.json does curently NOT contain the webfont line ... this will get fixed by the patch ... causeing the problem it is said to solve to appear for everyone

**Comment by oetiker** [comment]
Instead of this patch, I would suggest to package the manifest sitting in framework with the npm release as this will make the npm release work the same a s the git version AND fix the compiler such that the resulting code will only try to load webfonts that have assets present or something ...

**Comment by derrell** [comment]
It seems inappropriate to approve this with a question still outstanding in [@oetiker's last response](https://github.com/qooxdoo/qooxdoo/pull/10043#issuecomment-697992839). He is suggesting an alternative to this PR...

**Comment by hkollmann** [comment]
The framework version contains stuff for the python tool chain - the one in the root not. That's the reason for the differentz versions.
Both versions contains the laoding of the webfonts.
Change of the compiler is another issue.

**Review by derrell — APPROVED** [review]

**Review by johnspackman — APPROVED** [review]

**Review by level420 — APPROVED** [review]

**Pull request merged**
