### PR TITLE
Small correction to the help text.

### PR DESCRIPTION
**Pull request by dgnthr**
A word was missing ;-)

### CODE REVIEW

**Review by level420 — APPROVED** [review]

**Review by cboulanger — APPROVED** [review]
By all means, I don't think this needs voting on :-)

**Review by cajus — APPROVED** [review]

**Comment by level420** [comment]
@cboulanger the rules (can't find them currently though) say that we need min. 2 approvals for documentation fixes.

**Comment by level420** [comment]
documentation fix only. 3 approvals. merging
thank you @dgnthr

**Comment by cboulanger** [comment]
Okey dokey…

**Pull request merged**
