### PR TITLE
Clean theme widgetbrowser version

### PR DESCRIPTION
**Pull request by sqville**
This is the widgetbrowser version of the Clean theme. It has been tested using the top 3 major browsers on both Windows 10 and the latest MacOS. This version works with the widgetbrowser app with two exceptions. qx-inset class gets demoted for some odd reason for textfields, and theme switching breaks when going from Clean to any other theme. I will continue to address these issues. I am submitting this PR as a means to get this process started, and to get help on these two outstanding issues. This PR directly addresses Enhancement Request #211  

**New\Unique feature of this theme:**
All decorator images, with the exception of treevirtual, have been replaced with code (pure qx, qx + CSS) or embedded SVG using the template class. Prime examples are: 

- arrows and radiobuttons (pure qx)

- checkbox and table select column button (qx + CSS)

- datefield and tree (embedded SVG)

**Design decisions to consider are as follows:**
1. Mixins are used to add new, themable fields to framework classes - See "qx.theme.Clean" for the exact list
2. "qx.ui.popup.Popup" is **patched** in order to include two new states, bottom and top placement, in order to know if a selectbox's popup is above or underneath the control (i recommend updating the framework itself in order to enable this feature, but it is here for now)
3. iconProps property is added to Atom so that Button appearance entries can change it's image based on button states (hover, focus, etc)
4. "html" property has been added to Image so that SVG (or HTML) can be added and manipulated by the Image's parent container (i.e. Atom and HeaderCell). SVG code is centralized in the theme's "qx.theme.clean.Image" class as static entries
5. "freeStyleCss" is added to Decorator to allow for the addition of psudo classes (after and before) and custom CSS. Custom CSS is centralized in the theme's "qx.theme.clean.Image" class as static entries

Working demo can be found here: http://sqville.com/examples/widgetbrowser2018/index.html

I am committed to making this theme acceptable to all. Thank you for your consideration.

Chris (sqville)

### CODE REVIEW

**Comment by jpriebe** [comment]
Great work, Chris!  Qooxdoo team, please incorporate this!  We need a fresher theme for qooxdoo!

**Comment by cboulanger** [comment]
Hi! Thsi is really great work that will add significantly to the visual presentation of the framework. So we are very happy. Would you consider to [provide the theme as a contrib library](https://github.com/qooxdoo/qooxdoo-compiler/blob/master/docs/cli/contrib.md)? The problem with integrating code into the core is that that means the core development team takes responsibility for maintaining it. Since yours is a complex piece of code with a lot of thinking behind it, we are afraid we cannot do that. We'll be happy to integrate the theme in the demos etc. Thanks again!

**Comment by sqville** [comment]
Thank you, and yes, happy to provide the theme as a contrib library. I read through the instructions, a few times now, and the process is still unclear to me. Looks like I will have to trial-and-error my way through this to a contrib version. Question too. Does this mean that I need to change the namespace of my classes? i.e. from "qx.theme.Clean" to something like "**sqv**.theme.Clean"

**Comment by hkollmann** [comment]
Have you seen the travis Fails?

**Comment by oetiker** [comment]
@sqville you can look at this one for inspiration https://github.com/ITISFoundation/qx-osparc-theme

**Comment by cboulanger** [comment]
@sqville "sqv.theme.Clean" would be a good name, yes. We have also talked about recommending that contrib creators use the pattern (in your case) "gh.sqville.theme.Clean" to indicate that the contrib is hosted on github under the given username, but it is totally up to you how to name it.

**Comment by sqville** [comment]
Thanks team! I addressed all the Travis Fails. I will make the switch to a contrib over the holidays and announce it's readiness over gitter, and anywhere else you all recommend.

**Comment by sqville** [comment]
Added as a contrib - https://github.com/sqville/sqv-qxthemes
Hope i set it up correctly

**Comment by oetiker** [comment]
closed PR since this is now a contrib

**Pull request closed without merging**
