### PR TITLE
add some documentation to qxWeb.

### PR DESCRIPTION
**Pull request by hkollmann**
add generating off example index.html

This could be backported to v6.0.0

### CODE REVIEW

**Review by level420 — APPROVED** [review]

**Review by oetiker — APPROVED** [review]
backport would be great

**Review by derrell — APPROVED** [review]

**Review by cboulanger — APPROVED** [review]

**Comment by cboulanger** [comment]
You can "backport" the docs by directly pushing to https://github.com/qooxdoo/documentation/tree/gh-pages/6.0

**Comment by hkollmann** [comment]
Can't.  The change is in CHANGELOG.md. That is not part of the doc directory yet

**Review by johnspackman — APPROVED** [review]

**Comment by cboulanger** [comment]
thank you @hkollmann !

**Pull request merged**
