### PR TITLE
cherry picked PRs for 5.0.3 maintainance release

### PR DESCRIPTION
**Pull request by level420**
List of PRs: https://github.com/qooxdoo/qooxdoo/milestone/64?closed=1

### CODE REVIEW

**Comment by cboulanger** [comment]
Thank you for this!

**Review by cboulanger — DISMISSED** [review]

**Review by oetiker — DISMISSED** [review]

**Review by derrell — DISMISSED** [review]
There's a lot here. I did a look-through, and it looks good... and there *should* be nothing here that hasn't already been approved through the PR process for 6.0.

**Review by cajus — DISMISSED** [review]

**Comment by level420** [comment]
Sorry. missed most of the needed version changes :unamused:

**Review by hkollmann — APPROVED** [review]

**Comment by hkollmann** [comment]
What's the problem with travis checks?

**Comment by level420** [comment]
@hkollmann the PR does only add a few fixes to branch_5_0_x, but does not change anything regarding fixing tests or in the configuration/definition of the travis runs. Therefore the failing tests which failed before this PR will also fail with this PR. Of course ideally the PR would also fix all bugs in the tests, but I don't think we can/should afford the time to do so. 
Our goal should be to release 6.0.0 asap.

**Review by oetiker — APPROVED** [review]

**Review by derrell — APPROVED** [review]

**Review by cajus — APPROVED** [review]

**Review by johnspackman — APPROVED** [review]

**Pull request merged**
