### PR TITLE
add missing grunt stuff

### PR DESCRIPTION
**Pull request by hkollmann**
in august 2017 there was grunt stuff deleted which is needed for creating the docs. This PR reverts the deletion

### CODE REVIEW

**Comment by johnspackman** [comment]
I'm not familiar with this code, but it appears that it's just a wrapper around the generator - that it just automatically imports individual generator jobs into grunt as tasks.  Is that right?  In which case the build process could just call generator directly instead of going via grunt in the first place

**Comment by hkollmann** [comment]
That's an good idea. But not my intention yet. I just want to fix the build process.

**Review by cboulanger — APPROVED** [review]
If it is necessary to fix failing tests/cronjobs, sure.

**Review by johnspackman — APPROVED** [review]

**Review by level420 — APPROVED** [review]
I'm not really familiar with grunt, but I'm trusting @hkollmann here.

**Comment by hkollmann** [comment]
Here the error message from travis build log:

```

Loading "Gruntfile.js" tasks...ERROR

>> Error: Cannot find module './config/application.js'

Warning: Task "api" not found. Use --force to continue.
```

**Review by oetiker — APPROVED** [review]

**Review by cajus — APPROVED** [review]

**Pull request merged**
