### PR TITLE
cherry picked PRs from master to branch_5_0_x

### LINKED ISSUE #9623: Firefox 65 table scroll by keyboard
In Firefox 65 is no longer possible to change the row selection by keyboard.

The behaviour can be replicated in playgroud http://www.qooxdoo.org/current/demobrowser/#table~Table.html 
Select a row with a mouse click and try use keyboard arrows up and down to move selection. It takes no effect. With other browser (eg. Edge or Chrome) the focus and selection successful changes.

### PR DESCRIPTION
**Pull request by level420**
This started with a simple attempt to fix #9629, but escalated into a mass cherry-picking PR from master, trying to succeed the testrunner runs on chrome and firefox.

### CODE REVIEW

**Review by cboulanger — DISMISSED** [review]

**Comment by level420** [comment]
Pushed some more cherry-picked PRs with the intention to fix the tests. Here locally down from about 100 failing tests to 36. It's a hard job to identify all the those PRs which fixed the tests.

BTW: @oetiker ported the travis tests back on 12. Aug 2018: https://github.com/qooxdoo/qooxdoo/pull/9125 to branch_5_0_x where the travis job promptly failed: https://travis-ci.org/qooxdoo/qooxdoo/builds/151754600 for firefox with 86 failed tests and chrome with 95 failed tests.

At some point merging was blocked per rule when the travis check failed, thus not allowing us to merge anymore in branch_5_0_x

**Comment by level420** [comment]
Now we have 31 tests failing for firefox and 31 tests failing for chrome.

**Review by johnspackman — DISMISSED** [review]

**Review by johnspackman — DISMISSED** [review]

**Review by hkollmann — APPROVED** [review]

**Comment by cboulanger** [comment]
After @level420 has put so much work into this, we should really do something with it. Why don't we create a 5.0.4-beta release and ask people to test it?

**Review by cboulanger — APPROVED** [review]

**Comment by cboulanger** [comment]
@level420 Dietrich, do you have some updates on this?

**Pull request closed without merging**
