### PR TITLE
fixes a bug (which caused qx.dev.unit.Sinon to crash es6ify)

### PR DESCRIPTION
**Pull request by johnspackman**

### CODE REVIEW

**Review by cboulanger — APPROVED** [review]

**Comment by hkollmann** [comment]
And how can we fix the framework?

**Comment by johnspackman** [comment]
> And how can we fix the framework?

Do you mean the performance PR?

**Review by oetiker — APPROVED** [review]

**Review by level420 — APPROVED** [review]

**Comment by hkollmann** [comment]
Yes. I mean we run es6ify on the whole code base and do not know which parts are affected by this bug. I think it is neccessary to es6ify again. Or what do you think?

**Review by hkollmann — APPROVED** [review]

**Comment by johnspackman** [comment]
No it should be fine - the bug is that when an ES6 Symbol is used as a key in an object literal where the value is a function, so it was just that es6ify is being tripped up by the updated Sinon.js file only.

**Comment by hkollmann** [comment]
So test failures https://github.com/qooxdoo/qooxdoo/pull/10347 has another reason

**Comment by johnspackman** [comment]
yes :(

**Comment by hkollmann** [comment]
assuming your permission i fixed it directly in your branch.

**Review by derrell — APPROVED** [review]

**Pull request merged**
