### PR TITLE
Add support for building site data directly to gh-pages

### PR DESCRIPTION
**Pull request by cajus**
Needs DEPLOY_KEY from a user that has write access to qx.gh-pages.io to be set in the travis-ci console.

### CODE REVIEW

**Comment by oetiker** [comment]
you are deploying for every round of a matrix build, right ?

what happens when a PR gets tested, does this use the DEPLOY_KEY too ?

**Comment by cajus** [comment]
Why do you think I'm doing it?

**Comment by cajus** [comment]
No PRs are tested. Just master branch and tags.

**Comment by oetiker** [comment]
hihi ... just let me know when you need me todo anything :)

**Comment by cajus** [comment]
Closing this one to avoid multiple test builds. Will re-open it later on.

**Pull request closed without merging**
