### PR TITLE
Create FUNDING.yml [skip-travis]

### PR DESCRIPTION
**Pull request by zaucker**
Display a sponsor button on GitHub leading to our page at https://ko-fi.com/qooxdoo.
The ko-fi page is connected to our stripe account which soon will be connected to our bank account.

### CODE REVIEW

**Comment by derrell** [comment]
@zaucker, thanks for working on this! Much appreciated!

Suggestion: We don't have a large enough following, nor expect to any time really soon, for $3 cups of coffee to make any sense. We're really looking for meaningful donations (well?) upwards of $100. I'd recommend not indicating that we're looking for trivial donations with "cup of coffee" and $3.

Others' thoughts on this?

**Comment by lucapivato** [comment]
Maybe do 2 or 3 simple levels ($500, $2000, $5000) and a page showing the sponsors?

**Comment by zaucker** [comment]
> @zaucker, thanks for working on this! Much appreciated!
> 
> Suggestion: We don't have a large enough following, nor expect to any time really soon, for $3 cups of coffee to make any sense. We're really looking for meaningful donations (well?) upwards of $100. I'd recommend not indicating that we're looking for trivial donations with "cup of coffee" and $3.
> 
> Others' thoughts on this?

I changed the "unit" to $100. The catch with the free ko-fi account is that the "cup of coffee" metaphor cannot be changed.
At this point I don't really want spend $6/month on the gold upgrade.

I guess we'll have to go for a custom Stripe connection: https://stripe.com/docs/payments/checkout, anybody volunteering to add such a setup to the Qooxdoo home page?

**Comment by zaucker** [comment]
> Maybe do 2 or 3 simple levels ($500, $2000, $5000) and a page showing the sponsors?

As far as I can tell ko-fi doesn't have this option. But probably this can be done with the custom Stripe connection I mentioned.

**Review by cboulanger — APPROVED** [review]

**Review by johnspackman — APPROVED** [review]

**Review by oetiker — APPROVED** [review]

**Review by hkollmann — APPROVED** [review]

**Review by level420 — APPROVED** [review]

**Comment by tcsaddul** [comment]
I liike the idea of @lucapivato as I intend to donate more and a 5k would be a nice target.  Maybe 5k for "Platinum" sponsor, 2k for "Gold", 500 for "Silver", 100 for "Backer" and Cup/s of Coffee are nice additions.

**Comment by zaucker** [comment]
> I liike the idea of @lucapivato as I intend to donate more in the future and a 5k would be a nice target. Maybe 5k for "Platinum" sponsor, 2k for "Gold", 500 for "Silver", 100 for "Backer" and Cup/s of Coffee are nice additions.

It seems we are going to need a couple of different options, both for donations (one-time, repeating, pre-defined and open amounts, ...). And also for mentioning the sponsors (e.g, a list for the smaller ones and perhaps a separate page for a short company/product presentation with links to either their home page or the real-life page).

As of now there is a donation button at the top left of the homepage leading to the page https://liberapay.com/qooxdoo.org/donate, but this is only for repeating donations. As our bank account is not yet active, please wait a couple of days until we have things organised a bit more.

**Pull request merged**
