### PR TITLE
Edit desktop docs

### PR DESCRIPTION
**Pull request by goldim**
- grammar fix
- broken images fix
- fix wrong and bad links
- misspleling fix

### CODE REVIEW

**Review by cboulanger — APPROVED** [review]
Thank you!

**Review by oetiker — APPROVED** [review]
wow! great work!

**Review by hkollmann — APPROVED** [review]

**Comment by goldim** [comment]
It's not fully done at this moment. I'll try to finish left part of docs on these days.

**Review by derrell — APPROVED** [review]
Nice work! I don't agree with some of your changes, where the original text could impart a bit of additional meaning over the new text, e.g., "some of the icons" vs "some icons", but the new text isn't wrong so I didn't request reverting those. It's great to clean up the documentation!

**Comment by goldim** [comment]
@derrell could you point it out with comments on appropriate lines please? I could revert those you don't like. Except "some of them".

**Comment by derrell** [comment]
Not necessary. As I said, the changes you made are not incorrect. Let 'em ride.

**Review by level420 — APPROVED** [review]

**Pull request merged**
