### PR TITLE
Fix a serious error when maintaining addListenerOnce listener removal.

### PR DESCRIPTION
**Pull request by cajus**
When you add two _addListenerOnce_ calls with a different context, the second one gets removed after the first one was executed.

There's one place where it is even visible. Open the [current devel playground](http://qooxdoo.github.io/devel/playground) and take a look at the "Playground" string on the top left. It is cut off by an ellipsis.

### CODE REVIEW

**Comment by cajus** [comment]
This makes a couple of tests fail. Most likely because they're not cleaned up properly. Will update the PR soon in order to fix them.

**Comment by cajus** [comment]
Thanks @peuter ;-)

**Comment by peuter** [comment]
You`re welcome ;-)

**Comment by level420** [comment]
Sounds all reasonable. Thank you @cajus 
I think we should merge.

**Comment by johnspackman** [comment]
looks good to me :)

**Comment by oetiker** [comment]
yep :)

**Pull request merged**
