### PR TITLE
Auto hide fix

### PR DESCRIPTION
**Pull request by FriedrichF**
Because there is no null check before I get the autoHide Property there can be an Exception Thrown.

### CODE REVIEW

**Comment by FriedrichF** [comment]
Sorry for that!

**Review by derrell — APPROVED** [review]

**Review by johnspackman — APPROVED** [review]

**Comment by oetiker** [comment]
note, there are conflicts with this branch

**Review by cajus — APPROVED** [review]

**Review by oetiker — APPROVED** [review]
maybe squash it when merging ...

**Review by patrick-fischer-hirschstein — APPROVED** [review]

**Review by level420 — APPROVED** [review]

**Comment by level420** [comment]
5 approvals, merging.
thank you @FriedrichF

**Pull request merged**
