### PR TITLE
Theming doesn't support background images with spaces in their names

### PR DESCRIPTION
**Pull request by mrfeet**
#9674

### CODE REVIEW

**Review by johnspackman — DISMISSED** [review]

**Review by cboulanger — DISMISSED** [review]

**Review by derrell — DISMISSED** [review]
I'd sure like to know the reason that data URLs were being treated differently before. It's as if non-data URLs couldn't be quoted, so only data URLs were. This has the potential to break existing code if there are cases were quoting the URL causes problems.

**Comment by johnspackman** [comment]
this may explain it: https://stackoverflow.com/questions/2168855/is-quoting-the-value-of-url-really-necessary

Apparently "older browsers" request once with quotes and once without

**Comment by cboulanger** [comment]
Since we don't support older browsers anymore and the standard seems to be to recommend quotes, the PR seems sensible. 

One of the posts says

"The unquoted version is only supported for legacy reasons and needs special parsing rules (for escape sequences, etc.), thus being cumbersome and not supporting url-modifiers."

**Review by hkollmann — DISMISSED** [review]

**Review by oetiker — DISMISSED** [review]

**Comment by hkollmann** [comment]
You Need to fix the tests:

https://travis-ci.org/qooxdoo/qooxdoo/jobs/532813235:


Firefox 66.0.0 (Linux 0.0.0) qx.test.bom.element Background:testGetStyles FAILED

	Do not use "'" for image urls!: Expected 'url(foo/bar/baz.gif)' but found 'url('foo/bar/baz.gif')'!

		qx.core.AssertionError.constructor:326

		qx.core.Assert.__fail:1179

		qx.core.Assert.assertEquals:4808

		qx.type.BaseString.assertEquals:779

		qx.test.bom.element.Background.testGetStyles:7

		qx.dev.unit.TestFunction:1450

		qx.dev.unit.TestResult.run:5892

		qx.dev.unit.TestFunction.run:1287

		.runTest://travis-job-1a6258c3-1d7f-486b-b9c2-81d8884a92f0:9876node_modules/karma-qooxdoo/qooxdoo-adapter.js

.

Firefox 66.0.0 (Linux 0.0.0) qx.test.bom.element Background:testCompile FAILED

	Compiled CSS string is not valid!: Expected 'background-image:url(foo/bar/baz);background-position:0 0;background-repeat:no-repeat;' but found 'background-image:url('foo/bar/baz');background-position:0 0;background-repeat:no-repeat;'!

		qx.core.AssertionError.constructor:326

		qx.core.Assert.__fail:1179

		qx.core.Assert.assertEquals:4808

		qx.type.BaseString.assertEquals:779

		qx.test.bom.element.Background.testCompile:7

		qx.dev.unit.TestFunction:1450

		qx.dev.unit.TestResult.run:5892

**Comment by hkollmann** [comment]
@mrfeet : Is it possible for you to fix the tests?

**Comment by hkollmann** [comment]
@mrfeet : if it's not possible for you to fix - should i commit to your repos?

**Comment by mrfeet** [comment]
I’ll give it a go!

**Review by hkollmann — APPROVED** [review]

**Review by cboulanger — APPROVED** [review]

**Review by derrell — APPROVED** [review]

**Review by oetiker — APPROVED** [review]

**Review by level420 — APPROVED** [review]

**Comment by level420** [comment]
Full quorum. mergeing
thank you @mrfeet

**Pull request merged**
