### PR TITLE
Add framework testing

### PR DESCRIPTION
**Pull request by hkollmann**
Just run qx test in test/framework.

Needs some work to fix the 107 tests which are not ok. See appended file.

[fehler.txt](https://github.com/qooxdoo/qooxdoo/files/5875317/fehler.txt)

### CODE REVIEW

**Comment by hkollmann** [comment]
IMHO we can release version 6 with this and fix the tests after releasing.

**Review by cboulanger — APPROVED** [review]

**Review by johnspackman — APPROVED** [review]

**Comment by johnspackman** [comment]
> IMHO we can release version 6 with this and fix the tests after releasing.

To put this into perspective that's 107 failures out of over 3,000 tests, and IMHO many of those errors suggest that this could be due to changes in the environment (eg I think that some tests are dependant on a specific theme / theme appearance, and there's a load tests with timeouts).  Many of the errors are related to server I/O or themes, the code has not been changed for either of those areas (AFAICR) but we no longer have a php/python backend to test against.

I agree with @hkollmann lets release now

**Comment by cboulanger** [comment]
@hkollmann Can you remove 
- https://github.com/qooxdoo/qooxdoo/blob/master/test/run-all-tests
- https://github.com/qooxdoo/qooxdoo/blob/master/test/readme.md
with this PR ? They describe what I intended to add but won't be able to, before release. Once we have working code in place, we can re-add it.

**Review by oetiker — APPROVED** [review]

**Comment by hkollmann** [comment]
Having this test case:

`    "test: superclass calls aka basecalls (constructor and methods)" : function()
    {
      qx.Bootstrap.define("qx.test.Car",
      {
        construct : function(name) {
          this._name = name;
        },

        members :
        {
          _name: null
        }
      });

      var car = new qx.test.Car("Audi");
      this.assertEquals("Audi", car.getName());

      qx.Bootstrap.define("qx.test.Bmw",
      {
        extend : qx.test.Car,
        construct : function(name, prize) {
          this.base(arguments, name);
        },

        members :
        {
        },

        statics : { WHEELS : 4 }
      });
      var bmw = new qx.test.Bmw("bmw", 44000);
      this.assertEquals("bmw", bmw.getName());
      qx.Class.undefine("qx.test.Car");
      qx.Class.undefine("qx.test.Bmw");
    },
`

Translated into:

`
  "test: superclass calls aka basecalls (constructor and methods)": function testSuperclassCallsAkaBasecallsConstructorAndMethods() {
        qx.Bootstrap.define("qx.test.Car", {
          construct: function construct(name) {
            this._name = name;
          },
          members: {
            _name: null
          }
        });
        var car = new qx.test.Car("Audi");
        this.assertEquals("Audi", car.getName());
        qx.Bootstrap.define("qx.test.Bmw", {
          extend: qx.test.Car,
          construct: function construct(name, prize) {
            qx.test.Car.constructor.call(this, name);
          },
          members: {
          },
        });
        var bmw = new qx.test.Bmw("bmw", 44000);
        this.assertEquals("bmw", bmw.getName());
        qx.Class.undefine("qx.test.Car");
        qx.Class.undefine("qx.test.Bmw");
      },
`

The call ` qx.test.Car.constructor.call(this, name);` do not call the previous declared car constructor.

@johnspackman : any idea why? Compiler error?

**Comment by johnspackman** [comment]
this is fixed in a PR Im about to issue

**Comment by johnspackman** [comment]
The unit tests now run in the compiler-based TestRunner, with the exception of the list below.  However there are a number of other tests which still fail in TestTapper, but these are down to the environment (eg theme and/or locale) and should not hold up release.

Framework PR https://github.com/qooxdoo/qooxdoo/pull/10104
Compiler PR https://github.com/qooxdoo/qooxdoo-compiler/pull/801

qx.test.io.remote.* - not tested because we do not have a back end
qx.test.io.rest.* - not tested because we do not have a back end
qx.test.bom.rest.* - not tested because we do not have a back end

qx.test.lang.normalize.Date:test - broken with negative numbers; have standards changed??
qx.test.locale.Locale:testMacCtrl - key names not available as a translation - is this in addition to cldr?  This may be a missing compiler feature

**Review by derrell — APPROVED** [review]

**Review by level420 — APPROVED** [review]

**Comment by cboulanger** [comment]
Thank you @hkollmann !

**Pull request merged**
