### PR TITLE
adding ignoreUndeclaredPrivates to @lint hint

### PR DESCRIPTION
**Pull request by thron7**
This solves the issue with qx.test.Mixin's __b. See the Mixin class for @lint syntax.
I also fixed the framework's "lint-test" job so that it acutally works :-).

I'll update the manual once the PR is accepted.

### CODE REVIEW

**Comment by level420** [comment]
@thron7 Thank you for you PR. As from the gitter chat: I still think this PR is still needed. We should revert the ugly "hack" this.__b vs. this["__b"] which is only there to trick lint.

**Comment by oetiker** [comment]
@level420 and note that as @derrell pointed out, mixins can not access private variables of the class they are being mixed into

**Comment by level420** [comment]
@oetiker yes thats true, but this is not the case here

**Comment by thron7** [comment]
@level420 Done as requested (including squashing commits).

**Comment by level420** [comment]
Thank you thron7.

**Comment by level420** [comment]
:ballot_box_with_check: CALL FOR VOTE

**Comment by level420** [comment]
4 Votes. More than 2 business days.
Merging.
Thank you @thron7

**Pull request merged**
