### PR TITLE
fixes warnings

### PR DESCRIPTION
**Pull request by johnspackman**
fixes some warnings in line with changes in https://github.com/qooxdoo/qooxdoo-compiler/pull/493 and https://github.com/qooxdoo/qooxdoo-compiler/pull/504

### CODE REVIEW

**Review by level420 — APPROVED** [review]

**Review by cboulanger — APPROVED** [review]

**Review by hkollmann — APPROVED** [review]

**Review by hkollmann — CHANGES_REQUESTED** [review]
old lint needs the deleted ignores!

**Review by oetiker — APPROVED** [review]

**Comment by johnspackman** [comment]
@hkollmann fixed

**Review by hkollmann — APPROVED** [review]
That's it!

**Comment by cboulanger** [comment]
Would such a PR, which does not change the operative code itself, qualify for being categorized as "Hotfix" or a yet-to-be created category of "Minor change" that could go with fewer than 5 approvals? I think we should be able to move faster with these kind of changes...

**Review by derrell — APPROVED** [review]

**Comment by derrell** [comment]
I don't think a change such as this should be fast-tracked. We fast-track hotfixes because they are time-critical. What defines a "minor change" though? I'd just keep it as is for anything that doesn't require extreme speed.

**Pull request merged**
