### PR TITLE
Fixes #9488: Dispose the previous layout in qx.ui.form.List on orientation change

### LINKED ISSUE #9488: qx.ui.form.List._applyOrientation leaks previous layout instance
When changing the orientation of a list widget from horizontal to vertical or vice-versa:

https://github.com/qooxdoo/qooxdoo/blob/7fa76d1550a4186a6d8f3c54d50e961c34914bcb/framework/source/class/qx/ui/form/List.js#L272

the previous layout instance (qx.ui.layout.VBox or qx.ui.layout.HBox) is not disposed.

### PR DESCRIPTION
**Pull request by level420**
See https://github.com/qooxdoo/qooxdoo/issues/9488

### CODE REVIEW

**Comment by oetiker** [comment]
I thought we do not have to dispose of things anymore unless they have created DOM elements which have to be removed...?

**Review by hkollmann — APPROVED** [review]

**Comment by level420** [comment]
@oetiker When digging down you'll find in the end the following destructor in `qx.ui.layout.Abstract`: https://github.com/qooxdoo/qooxdoo/blob/master/framework/source/class/qx/ui/layout/Abstract.js#L257-L259 where we could end having a circular ref from the widget which sets the layout to the layout with holds the widget instance in `this.__widget`. This reference should be broken.
There is  similar code in the framework e.g. in https://github.com/qooxdoo/qooxdoo/blob/master/framework/source/class/qx/ui/container/SlideBar.js#L273-L315

**Comment by oetiker** [comment]
@level420 ok!

**Review by oetiker — APPROVED** [review]

**Review by derrell — APPROVED** [review]

**Comment by level420** [comment]
btw: the failing tests are unrelated.

**Comment by johnspackman** [comment]
Even with circular references, this shouldn't be necessary on 6.x - the garbage collector will be able to handle that kind of reference and not cause a leak. There's certainly no harm in adding this in, especially if it's backported to 5.x (not sure we need to do that though)

**Review by johnspackman — APPROVED** [review]

**Comment by hkollmann** [comment]
Sometimes a new start of the tests helps!

**Comment by level420** [comment]
@hkollmann thank you for restarting the tests. I've done that 2 times before you've done it with no luck!

**Review by cboulanger — APPROVED** [review]

**Comment by hkollmann** [comment]
5 approvals, 6 days, merged.
Thanks, @level420!

**Pull request merged**
