### PR TITLE
fix deploy to npm 4 - update to node 11

### PR DESCRIPTION
**Pull request by hkollmann**

### CODE REVIEW

**Comment by cboulanger** [comment]
Why is this necessary? Most people will use node 8 or 10 ...

**Comment by hkollmann** [comment]
It's a test if it fixes 

```
$ npm publish --access public --verbose

npm info it worked if it ends with ok

npm verb cli [ '/home/travis/.nvm/versions/node/v8.9.1/bin/node',

npm verb cli   '/home/travis/.nvm/versions/node/v8.9.1/bin/npm',

npm verb cli   'publish',

npm verb cli   '--access',

npm verb cli   'public',

npm verb cli   '--verbose' ]

npm info using npm@5.5.1

npm info using node@v8.9.1

npm verb npm-session d5e69682b76f88d9

npm verb publish [ '.' ]

npm info lifecycle @qooxdoo/framework@6.0.0-beta-20190627-1255~prepublish: @qooxdoo/framework@6.0.0-beta-20190627-1255

npm info lifecycle @qooxdoo/framework@6.0.0-beta-20190627-1255~prepare: @qooxdoo/framework@6.0.0-beta-20190627-1255

npm info lifecycle @qooxdoo/framework@6.0.0-beta-20190627-1255~prepublishOnly: @qooxdoo/framework@6.0.0-beta-20190627-1255

npm info lifecycle @qooxdoo/framework@6.0.0-beta-20190627-1255~prepack: @qooxdoo/framework@6.0.0-beta-20190627-1255

npm info lifecycle @qooxdoo/framework@6.0.0-beta-20190627-1255~postpack: @qooxdoo/framework@6.0.0-beta-20190627-1255

npm verb getPublishConfig undefined

npm verb mapToRegistry no registry URL found in name for scope @qooxdoo

npm verb publish registryBase https://registry.npmjs.org/

npm verb stack Error: "toString()" failed

npm verb stack     at stringSlice (buffer.js:576:45)

npm verb stack     at Buffer.toString (buffer.js:631:10)

npm verb stack     at RegClient.putFirst (/home/travis/.nvm/versions/node/v8.9.1/lib/node_modules/npm/node_modules/npm-registry-client/lib/publish.js:103:23)

npm verb stack     at /home/travis/.nvm/versions/node/v8.9.1/lib/node_modules/npm/node_modules/npm-registry-client/lib/publish.js:54:14

npm verb stack     at ConcatStream.<anonymous> (/home/travis/.nvm/versions/node/v8.9.1/lib/node_modules/npm/node_modules/npm-registry-client/node_modules/concat-stream/index.js:36:43)

npm verb stack     at emitNone (events.js:111:20)

npm verb stack     at ConcatStream.emit (events.js:208:7)

npm verb stack     at finishMaybe (/home/travis/.nvm/versions/node/v8.9.1/lib/node_modules/npm/node_modules/readable-stream/lib/_stream_writable.js:607:14)

npm verb stack     at endWritable (/home/travis/.nvm/versions/node/v8.9.1/lib/node_modules/npm/node_modules/readable-stream/lib/_stream_writable.js:615:3)

npm verb stack     at ConcatStream.Writable.end (/home/travis/.nvm/versions/node/v8.9.1/lib/node_modules/npm/node_modules/readable-stream/lib/_stream_writable.js:571:41)

npm verb stack     at ReadStream.onend (_stream_readable.js:595:10)

npm verb stack     at Object.onceWrapper (events.js:313:30)

npm verb stack     at emitNone (events.js:111:20)

npm verb stack     at ReadStream.emit (events.js:208:7)

npm verb stack     at endReadableNT (_stream_readable.js:1056:12)

npm verb stack     at _combinedTickCallback (internal/process/next_tick.js:138:11)

npm verb cwd /home/travis/build/qooxdoo/qooxdoo

npm verb Linux 4.4.0-101-generic

npm verb argv "/home/travis/.nvm/versions/node/v8.9.1/bin/node" "/home/travis/.nvm/versions/node/v8.9.1/bin/npm" "publish" "--access" "public" "--verbose"

npm verb node v8.9.1

npm verb npm  v5.5.1

npm ERR! "toString()" failed

npm verb exit [ 1, true ]


npm ERR! A complete log of this run can be found in:

npm ERR!     /home/travis/.npm/_logs/2019-06-27T13_10_36_548Z-debug.log

```

**Comment by hkollmann** [comment]
I have no idea what npm want's to say.
If this works i will try an npm install npm@latest -g

**Review by cboulanger — APPROVED** [review]

**Review by derrell — APPROVED** [review]

**Comment by cboulanger** [comment]
Merging hotfix, thank you @hkollmann

**Pull request merged**
