### PR TITLE
Fixed #9906: The hideAll function of menu manager had the wrong context.

### LINKED ISSUE #9906: The menu does not always close
**Describe the bug**
The menu is not closed if a modal window opens. It also stays in front of the blocker. Seems to be broken since commit 8a382b3da40800e59bec78101d32ef2ac7ba1454.

**To Reproduce**
Here is a playground example: https://tinyurl.com/sq3wcpx

**Screenshots**
image

**Desktop (please complete the following information):**
Tested on windows with Chrome and FF.

### PR DESCRIPTION
**Pull request by Holdwyn**

### CODE REVIEW

**Review by derrell — CHANGES_REQUESTED** [review]
Although this probably is fixing a bug, it will have long-ranging effects on backward compatibility. Many apps may break. I'm not sure what the right solution is...

Also, the change from 100ms to 0ms may be wrong. Those delays are typically to allow the rendering queue to flush, and simply enquing it to run again immediately may not do the job. Those can be race conditions that may not show themselves immediately, but can be very hard to track down.

**Comment by Holdwyn** [comment]
> Although this probably is fixing a bug, it will have long-ranging effects on backward compatibility. Many apps may break. I'm not sure what the right solution is...
> 
> Also, the change from 100ms to 0ms may be wrong. Those delays are typically to allow the rendering queue to flush, and simply enquing it to run again immediately may not do the job. Those can be race conditions that may not show themselves immediately, but can be very hard to track down.

I guess there is no need for a real timeout, it is enough to wait for the javascript tread to end. I tested to not raise the bug #9645 again. The click event still works with Firefox. With 100ms there is a noticeable flickering of the menu over the (colored) blocker.

**Review by derrell — APPROVED** [review]
The part I was most concerned about was a possible backward-compatibility issue, but re-reviewing, I see that it's not calling a user's callback function; it's calling a very specific function in the framework, which does in fact expect a particular context. I think this is a very appropriate change.

I'm still a bit concerned about the change in timeout value, but I suspect that your argument is valid, and that only a wait for the current JavaScript loop iteration context to end is adequate.

**Review by johnspackman — APPROVED** [review]

**Review by hkollmann — APPROVED** [review]

**Review by cboulanger — APPROVED** [review]

**Review by level420 — APPROVED** [review]

**Comment by cboulanger** [comment]
Merging, thank you @Holdwyn !

**Pull request merged**
