### PR TITLE
Wrong syntax in qx.test.ui.basic.Atom test method declaration

### PR DESCRIPTION
**Pull request by level420**
There is accidentaly a string literal "test" in the method declaration.

### CODE REVIEW

**Comment by level420** [comment]
@zaucker could you please verify it this was a typo or something by intention? Thank you!

**Comment by zaucker** [comment]
@level420 This was unintentional. However, the string 'test' should be an argument of the call to qx.ui.basic.Atom('test'). I wonder how to fix this. I don't seem to be able to edit the file directly. Should I create a new pull request with the fix or can you fix your fix?

**Comment by level420** [comment]
@zaucker done (I think)

**Comment by zaucker** [comment]
Thanks. Let's see what travis says ... strange that the old version passed before.

**Comment by zaucker** [comment]
Travis timed out. Is there something to set the timeout higher? I restarted the one run that didn't finish.

**Comment by level420** [comment]
:ballot_box_with_check: CALL FOR VOTE

**Comment by zaucker** [comment]
Merged as we have more than 5 thumbsUp.

**Pull request merged**
