### PR TITLE
remove twitter app because it is not working in the moment

### PR DESCRIPTION
**Pull request by hkollmann**

### CODE REVIEW

**Review by cboulanger — APPROVED** [review]

**Comment by oetiker** [comment]
hmmm this is the only "complete" qooxdoo example app we have ... I guess we could replace the 'server' component with one which fakes twitter ...

**Comment by hkollmann** [comment]
I removed it yet - saved it. Let's release v6. I hope i found some time to move it to the new toolchain and update the docs then.
Up to then better remove it.

**Comment by hkollmann** [comment]
And we have a tutorial: http://www.qooxdoo.org/qxl.tutorial/

**Comment by hkollmann** [comment]
twitter app can be used as tutorial with less work. 
The docs must be cleaned up - the idenica service is unusable. It's replaced by a local file service.js which delivers some hardcoded text.
This should be enough for a desktop tutorial.

**Pull request closed without merging**
