### PR TITLE
qx.util.Uri.parseUri() goes wrong when @ in query #9402

### PR DESCRIPTION
**Pull request by mrfeet**

### CODE REVIEW

**Comment by johnspackman** [comment]
Following on from the conversation in https://github.com/qooxdoo/qooxdoo/issues/9402, while I agree with @derrell 's concerns about "where do we stop" I think that on balance I would vote for this because IMHO it's better to match browsers, especially when URLs are quite possibly entered by users who do not necessarily have respect for specs.

However - is there some way to reformat that regex?  I find it impossible to read and really difficult to evaluate the change.

**Comment by oetiker** [comment]
yes please if the regexp gets modified, please convert it into a more readable version ... like this for example (this is NOT the same regexp ... it just shows the concept)

```javascript
var urlRegex= new RegExp(''
  + /(?:(?:(https?|ftp):)?\/\/)/.source     // protocol
  + /(?:([^:\n\r]+):([^@\n\r]+)@)?/.source  // user:pass
  + /(?:(?:www\.)?([^\/\n\r]+))/.source     // domain
  + /(\/[^?\n\r]+)?/.source                 // request
  + /(\?[^#\n\r]*)?/.source                 // query
  + /(#?[^\n\r]*)?/.source                  // anchor
);
```

**Comment by level420** [comment]
@mrfeet could you please have a look into the changes requested by @oetiker and @johnspackman ? Thank you.

**Comment by mrfeet** [comment]
Sure I can try. Although it would make it harder to use a site like https://regex101.com/ to actually test the regex...

**Comment by mrfeet** [comment]
Not sure I can simplify it more than this, otherwise the groups are not matching the code anymore:

```
parser: {
         strict: new RegExp(''
			+ /^(?:([^:\/?#]+):)?/.source                                                                                   // protocol
			+ /(?:\/\/((?:(([^:@?]*)(?::([^:@?]*))?)?@)?((?:\[[0-9A-Fa-f:]+\])|(?:[^:\/?#\[\]]*))(?::(\d*))?))?/.source	// "//"(userid(:password)@)(domainname|ipv4address|ipv6address)
			+ /((((?:[^?#\/]*\/)*)([^?#]*))(?:\?([^#]*))?(?:#(.*))?)/.source                                                // (path)(?query)(#anchor)
			),
          loose:  new RegExp(''
			+ /^(?:(?![^:@?]+:[^:@?\/]*@)([^:\/?#.]+):)?/.source														// protocol
			+ /(?:\/\/)?/.source																						// "//"
			+ /((?:(([^:@?]*)(?::([^:@?]*))?)?@)?((?:\[[0-9A-Fa-f:]+\])|(?:[^:\/?#\[\]]*))(?::(\d*))?)/.source			// (userid(:password)@)(domainname|ipv4address|ipv6address)
			+ /(((\/(?:[^?#](?![^?#\/]*\.[^?#\/.]+(?:[?#]|$)))*\/?)?([^?#\/]*))(?:\?([^#]*))?(?:#(.*))?)/.source		// (path)(?query)(#anchor)
					)
}
```

**Comment by level420** [comment]
@mrfeet please change the PR based on your last suggestion. thank you.

**Comment by johnspackman** [comment]
Thank you @mrfeet for taking the time to reformat it, and I take your point about not being able to quickly copy & paste it into an online debugger/formatter.

Perhaps we should just treat regex's like this as binary data and expect it to be unreadable when in code, in which case we would rely on third party tools like https://regex101.com/ (a quick google shows up others too, eg https://www.debuggex.com/ and https://regexper.com/) to decode, debug, and test the expression?

That regexpr.com does visual diagram too which may be more effective than any text formatting we might be able to put in code.  

So despite having asked for reformatting, I'm now leaning towards putting it back the way it was originally in this PR (sorry @mrfeet !!) because out of two imperfect solutions, the first one is at least a plain vanilla regex that anything third party tool can understand.

**Review by cajus — APPROVED** [review]
I personally never used a @ inside of URL parmeters. If the specs say it's basically valid, I'm fine with changing the regexp. Although it's hard to see the changes in the diff viewer. Even if there are tools to visualize what's going on, both are complex enough to let you spend some minutes with analyzing them. I'd skip this as time does not allow it in the moment and trust the tests.

**Review by johnspackman — APPROVED** [review]

**Review by level420 — APPROVED** [review]
I'm trusting the tests.

**Comment by level420** [comment]
3 approvals, more than 2 business days, merging
thank you @mrfeet

**Pull request merged**
