### PR TITLE
fix `es6ify --arrowFunctions` and `lint --fix-jsdoc-params` commands

### PR DESCRIPTION
**Pull request by adrelino**
- default run (--arrowFunctions=careful) did not change ANY functions to arrowFunctions due to a small typo in `__pluginArrowFunctions`
- `this` as last arg was only removed for this.addListener, not if .addListener was called on another object, due to extra condition in `__pluginRemoveUnnecessaryThis`

### CODE REVIEW

**Comment by adrelino** [comment]
I tested the various transformations to arrowFunctions using this code:
```js
qx.Class.define("TestEs6ifyToArrowFunctions", {
  extend: qx.ui.core.Widget,

  construct() {
    super();

    this.addListener("appear", function (e) {
      console.log("this.appear");
    },this);

    var button1 = new qx.ui.form.Button("First Button", "icon/22/apps/internet-web-browser.png");
    button1.addListener("execute", function (e) {
      alert("Hello World 1!");
    },this);

    this.__button2 = new qx.ui.form.Button("Second Button", "icon/22/apps/internet-web-browser.png");
    this.__button2.addListener("execute", function (e) {
      alert("Hello World 2!");
    },this);

    qx.event.Timer.once(function () {
        console.log("once");
    }, this, 500);

    console.log(
      ["A", "B", "C"]
        .map(function (v) {
          return v.toLowerCase();
        }, this)
        .join(",")
    );

    ["A", "B", "C"].forEach(function (v) {
      let vv = v + v;
      this.logSpecial(vv);
    }, this);
  },

  members: {
    logSpecial(vv) {
      console.log(vv[0].toLowerCase() + ",");
    }
  }
});
```

To reproduce transformations of arrow functions in above code, qooxdoo was cloned inside the root of my project, and then I needed to bootstrap the compiler first
```
cd qooxdoo && ./bootstrap-compiler
```

Then I debugged the compiler (to come up with the fixes) using the commands
```js
node --inspect ../qooxdoo/bin/source/qx es6ify source/class/TestEs6ifyToArrowFunctions.js
```

**Review by johnspackman — APPROVED** [review]

**Comment by johnspackman** [comment]
nice catch 👍 ; sounds like we'll have another big PR with the results of es6ify

**Review by oetiker — APPROVED** [review]

**Review by cboulanger — APPROVED** [review]

**Review by hkollmann — APPROVED** [review]

**Review by cboulanger — APPROVED** [review]

**Comment by adrelino** [comment]
I also just added fixes for the `lint` command to this PR that are related to upgrading the codebase to proper es6.

Now, passing the `files` positional argument works also for fixing js doc params. Before it was just ignored. I did not find a way to include *.js files recursively using the `glob` package, but as a workaround there is a syntax using brackets and specifying every depth level, e.g. this is used for depth of 3, matching e.g. `Application.js, util/Util.js, ui/form/TimeField.js`:
```
lint --fix-jsdoc-params=type-first source/class/*/{,*/,*/*/}*.js
```

**Review by level420 — APPROVED** [review]

**Review by johnspackman — APPROVED** [review]

**Review by derrell — APPROVED** [review]

**Comment by hkollmann** [comment]
Thanks @adrelino !

**Pull request merged**
