### PR TITLE
Return removed children in _removeAll

### LINKED ISSUE #9030: qx.ui.toolbar.Toolbar.removeAll() doesn't return children array
qx.ui.toolbar.Toolbar.removeAll() doesn't return children array,
returns undefined instead

quick fix:

ToolBar.js

    // overridden
    _removeAll : function() {
      var ret = this.base(arguments);
      this._recalculateOverflow(null, 0);
      return ret;
    },

Regards, Johannes

### PR DESCRIPTION
**Pull request by level420**
as documented in https://github.com/qooxdoo/qooxdoo/blob/4bfad7f/framework/source/class/qx/ui/core/MChildrenHandling.js#L173

fixes #9030

### CODE REVIEW

**Comment by level420** [comment]
Sorry! Accidently created a branch in https://github.com/qooxdoo/qooxdoo

**Comment by oetiker** [comment]
looks good ... since adding a return value to a function that did NOT have a return value, should not have any negative impact IMHO ... but lets see if the tests agree

**Comment by cajus** [comment]
+1 from here, too

**Comment by level420** [comment]
I meant the fact that I created a branch in qooxdoo/qooxdoo and not in my fork. Is this something odd?

**Comment by oetiker** [comment]
you can just remove the branch after merging no harm done

**Comment by cajus** [comment]
Just remove the branch after it's merged. I don't see a problem there.

**Comment by oetiker** [comment]
https://github.com/qooxdoo/qooxdoo/branches

**Comment by level420** [comment]
I was worried about the two travis runs.

**Comment by oetiker** [comment]
one is for the new branch and one is for the PR

**Comment by oetiker** [comment]
what IS interesting that the new branch caused a rebuild of the website ... @cajus

**Comment by woprandi** [comment]
You should maybe add a unit test for that

**Comment by oetiker** [comment]
then the coverage would not drop :)

**Comment by level420** [comment]
Yes! I will add a unit test for that asap. But now from my form :-(

**Comment by woprandi** [comment]
Yeah, and also because it is a good practice to always add a unit test to prevent a bugfix to come-back :)

**Comment by level420** [comment]
So should I create a new PR based on my fork including the test or just merge this and create another PR with the test?

**Comment by level420** [comment]
Closing this one and creating a new one based on my fork.

**Pull request closed without merging**
