### PR TITLE
Initial commit for websocket.

### PR DESCRIPTION
**Pull request by stefanand**
As websockets have not yet been implemented, we have taken the first stumbling steps towards it.

This is not complete yet and under development.

We look at:
1. basic functionality
2. reconnection
3. fallback mechanisms
4. different send/receive, delegate and broadcast mechanisms

All suggestions are appreciated.

Stefan

### CODE REVIEW

**Comment by wittemann** [comment]
I think that this is not an issue anymore.

**Comment by v3ss0n** [comment]
So this was declined ?

**Comment by wittemann** [comment]
Yes, as we talked about it on the mailing list and thought that this might better a contribution.

**Comment by v3ss0n** [comment]
Would nice to have it inside qooxdoo , those migrated from sencha are asking for it and i am interested too. Do you guys accept  bounty source? In case we can crowd fund some features for community involvement and motivation. I do not see websocket contrib anywhere too.

**Comment by wittemann** [comment]
I'm not sure if it ended in a contrib in the end or not. Its up to the contributor.
No, we don't do any kind of bounty source. But we are open to any kind of contribution including its maintainership. Such a huge feature is not done with one pull request so having that in a contribution with full source code control for the maintainer is still my way to go in the first place. If any kind of contribution is well maintained and there is a huge demand to have in in the framework code source, we could move it over to the framework code.

**Pull request closed without merging**
