### PR TITLE
Fix for issue #9135

### PR DESCRIPTION
**Pull request by cajus**
This PR adds a flag to distinguish between the two possible message catalogues, in order to make the translation of CLDR provided objects possible.

See #9135

### CODE REVIEW

**Comment by level420** [comment]
@cajus could you please explain a bit the scenario where this is needed and how it is used? Thank you.

**Comment by cajus** [comment]
https://github.com/qooxdoo/qooxdoo/issues/9135 explains the problem.

**Comment by cajus** [comment]
If that's not enough: every time you want to use CLDR translated date (i.e. a weekday or a monthname), and write it out in a label (or the console), you're getting the cldr_foobar string instead of "Sonntag".

That is because qx holds translations in this.__translation, but the CLDR data lives in this.__locales.

translate() only looks in this.__translation.

**Comment by cajus** [comment]
As a result, I'm no storing the information what the source catalogue was - remembering it in translate().

**Comment by cajus** [comment]
@level420 Ok? ;-)

**Review by level420 — APPROVED** [review]
Understood!

**Review by johnspackman — APPROVED** [review]

**Review by derrell — APPROVED** [review]

**Review by zaucker — APPROVED** [review]

**Comment by level420** [comment]
4 approvals. more than 2 business days.
merging.
thank you @cajus

**Pull request merged**
