### PR TITLE
WIP - new documentation system

### PR DESCRIPTION
**Pull request by oetiker**
This is an experiment for converting our existing documentation to Markdown and also providing a publication system for it. In keeping with our 'all JS' strategy, I am planning on testing https://docsify.js.org/ as a system for publication of the documentation.

### CODE REVIEW

**Comment by cboulanger** [comment]
Sorry, but as I said on twitter, this doesn't make sense unless we have found a way replace the dynamic parts of RST which do not exist in MD.

**Comment by cboulanger** [comment]
Sorry for my last comment, I didn't mean to be rude. What I was trying to say is that I think we should have an example workflow first to see how to replace the dynamic features (or abandon them).

**Comment by oetiker** [comment]
@cboulanger can you point me to the 'dynamic' things you mean apart from the qooxdoo version number in the first index file

**Comment by cboulanger** [comment]
for example, here:

https://raw.githubusercontent.com/qooxdoo/qooxdoo/master/documentation/manual/source/pages/data_binding/data_binding.rst

or here:
https://github.com/qooxdoo/qooxdoo/blob/master/documentation/manual/source/pages/references.rst

it's all over the RST files...

**Comment by cboulanger** [comment]
Or here: 
https://github.com/qooxdoo/qooxdoo/blob/master/documentation/manual/source/pages/getting_started.rst

Containing variables, references and table of contents...

**Comment by hkollmann** [comment]
Maybe this could help to generate the toc:
https://github.com/remarkjs/remark-toc

**Comment by cboulanger** [comment]
Another point about documentation - how are we dealing with the fact that it is currently split into compiler and framework documentation. Shouldn't documentation be integrated? If we keep the repositories separate, we need some way for the documentation generator to integrate them (which should be possible with some hook scripts).

**Comment by cboulanger** [comment]
See also #9617

**Comment by oetiker** [comment]
or use the same system on both and just have links ... for now
and once compiler stabilizes merge it into the qooxdoo repo and also the documentation

**Comment by oetiker** [comment]
I have created a demo on https://github.com/oetiker/qooxdoo-docs

**Comment by hkollmann** [comment]
Could we close this?

**Pull request closed without merging**
