### PR TITLE
framework Manifest.json should not require anything

### PR DESCRIPTION
**Pull request by level420**
Both version and required version should be the same.

### CODE REVIEW

**Comment by cboulanger** [comment]
I think the require entry needs to be removed completely. It seems to me that a framework requiring itself doesn't make sense. The  dependency order is compiler -> framework . The framework itself shouldn't have a dependency on the compiler.

**Review by hkollmann — APPROVED** [review]

**Review by hkollmann — CHANGES_REQUESTED** [review]
IMHO @cboulanger is right!

**Comment by level420** [comment]
OK, then the complete `required` attribute should be removed?
https://github.com/qooxdoo/qooxdoo/blob/master/Manifest.json#L91-L94

**Comment by cboulanger** [comment]
I think it should be, but I have just seen that we made `requires` mandatory in the schema. This needs to be changed first, otherwise removing it breaks schema validation: 
https://github.com/qooxdoo/qooxdoo-compiler/blob/master/source/resource/qx/tool/schema/Manifest-1-0-0.json

**Review by hkollmann — APPROVED** [review]

**Comment by level420** [comment]
as now with https://github.com/qooxdoo/qooxdoo-compiler/issues/668 required isn’t mandatory anymore we could proceed with this PR

**Review by cboulanger — APPROVED** [review]

**Review by johnspackman — APPROVED** [review]

**Review by oetiker — APPROVED** [review]

**Review by derrell — APPROVED** [review]

**Pull request merged**
