### PR TITLE
 fix for  Mixin in derivated classes 

### PR DESCRIPTION
**Pull request by hkollmann**
fix for  https://github.com/qooxdoo/qooxdoo/issues/10355: Mixin in derivated classes

### CODE REVIEW

**Review by derrell — APPROVED** [review]

**Review by johnspackman — APPROVED** [review]

**Review by oetiker — APPROVED** [review]

**Review by cboulanger — APPROVED** [review]
Trusting you here, I have no idea what this does

**Comment by hkollmann** [comment]
.superclass.prototype.func calls the actual function of the base class whereas .prototype.base.func calls just acopy of base class function. This copy reflects the state during creation oft the class.
If you add an mixin this copy not longer actual so the changed function is not called.
This is done by call to .superclass.prototype.func

**Comment by johnspackman** [comment]
although I approved this yesterday, I'm having second thoughts that it's the right solution  - 

I'm trying to figure out why the methods have a `base` property at all, because this fix makes it look like it's not needed (it may have only been needed for the generator). 

Does this work if the superclass has a method with the same name which is added by a different mixin?

EG if A is the base class, B derives from A, and C derives from B; MA, MB, and MC are all mixins which all define a method `doSomething`, and where MA is included in A, MB in B, and MC in C.

Each mixin's `doSomething()` can call `super()`, so all three methods are called.  Same if A has `doSomething` and MA is not used

**Comment by hkollmann** [comment]
base is needed in Mixin.baseClassMethod to find original method if you use super() in an mixin.

**Comment by hkollmann** [comment]
Could you provide a test case for this?

Von meinem iPhone gesendet

**Comment by hkollmann** [comment]
testPatchMultiOverwrittenDerived() {
      qx.Class.define("qx.A", {
        extend: qx.core.Object,
        members: {
          sayJuhu() {
            return "A";
          }
        }
      });
      qx.Class.define("qx.B", {
        extend: qx.A,
        members: {
          sayJuhu() {
            return super() + " B";
          }
        }
      });
      qx.Class.define("qx.C", {
        extend: qx.B,
        members: {
          sayJuhu() {
            return super() + " C";
          }
        }
      });
      qx.Mixin.define("qx.MA", {
        members: {
          sayJuhu() {
            return super.sayJuhu() + " MA";
          },
        }
      });
      qx.Mixin.define("qx.MB", {
        members: {
          sayJuhu() {
            return super.sayJuhu() + " MB";
          },
        }
      });
      qx.Mixin.define("qx.MC", {
        members: {
          sayJuhu() {
            return super.sayJuhu() + " MC";
          },
        }
      });
      qx.Class.patch(qx.A, qx.MA);
      qx.Class.patch(qx.B, qx.MB);
      qx.Class.patch(qx.C, qx.MC);

      var o = new qx.C();
      this.assertEquals("A MA B MB C MC", o.sayJuhu());
      o.dispose();

    }

**Comment by hkollmann** [comment]
@johnspackman: This test is running. Is it what you ask for?

**Review by level420 — APPROVED** [review]

**Pull request merged**
