### PR TITLE
add new widgets to release notes

### PR DESCRIPTION
**Pull request by hkollmann**
to prepare publishing release 7.2

### CODE REVIEW

**Review by derrell — APPROVED** [review]

**Review by oetiker — APPROVED** [review]

**Comment by oetiker** [comment]
thios would be 7.2 ?

**Comment by derrell** [comment]
7.2 has already been released. This would be 7.3.

**Comment by hkollmann** [comment]
7.2 is not released! Last version is 7.1.1!

**Review by cboulanger — COMMENTED** [review]
Maybe add link to live ApiViewer?

**Comment by hkollmann** [comment]
we don'nt have one yet., Only after release.

**Review by cboulanger — APPROVED** [review]

**Review by johnspackman — APPROVED** [review]

**Review by level420 — APPROVED** [review]

**Pull request merged**
