### PR TITLE
Fix for #9719...

### PR DESCRIPTION
**Pull request by schnepe2**
`Conflicting property method qx.ui.splitpane.Splitter.isVisible with qx.ui.core.Widget`.
Property `visible` is for the whole widget (_as like all other widgets_),
property `knobVisible` is for the knob.

### CODE REVIEW

**Review by derrell — CHANGES_REQUESTED** [review]
Unfortunately, this will break existing apps. Any app that sets the `visible` property will be broken. Also, based on the comment removed from line 89 of Splitter.js, it looks like it's not just the knob that is suppsoed to be affected, but the entire slitter...

**Comment by schnepe2** [comment]
The `visible` property will affect the whole splitter!.
The `knowVisible` will only affect the knob.
This would fit the (former) comment even more!

But how can it be that every application has to tolerate this inconsistency and **warning**, while the implementation breaks all the expected API?
Everyone expects `visible` to affect the whole widget (that's what the warning is telling everybody) and those applications that might have used it in "the wrong" sense can easily be changed.

We've discussed this @ #9719 but no one seems to be able to present a cleaner solution. So after almost a year I thought: it is best to trigger this again.
I handle warnings as errors and this one cannot  be silenced by any non-framework action so far!

**Comment by oetiker** [comment]
yes, indeed the API is really not very satisfactory, I remember that we have accepted a PR for this thing already some time back so in case this made it worse, it would be fine to back it out in some way as it came in during development. Better to resolve the issue before we go final with 6.0

**Comment by oetiker** [comment]
in the worst case, we could provide a 'consistent' splitter under a new class name and deprecate the inconsistent one

**Review by derrell — CHANGES_REQUESTED** [review]
Although this change is not backward compatible, it does seem appropriate and now, as we're about to make a Major Release, is the right time to do this kind of thing. I approve this change, but mark it as Request changes so that we can discuss and ensure that we have the release documentation (upgrade instructions) written before merging.

**Review by oetiker — APPROVED** [review]

**Comment by cboulanger** [comment]
I support @derrell 's suggestion. @schnepe2 , can you add an entry to https://github.com/qooxdoo/qooxdoo/blob/master/CHANGELOG.md which explains the breaking change introduced by this PR?

**Comment by hkollmann** [comment]
And add a hint here: https://github.com/qooxdoo/qooxdoo/issues/9909?
Many thanks!

**Comment by schnepe2** [comment]
I've added the infos (to #9909 and to the PR).

Although I find it kind of questionable as there is no **change** when comparing to last release (5.0.2), just an added property.

**Review by cboulanger — APPROVED** [review]

**Comment by cboulanger** [comment]
@schnepe2 So maybe I misunderstood? I thought a breaking change was involved - @derrell, you said this was not backwards compatible? I have to admit I did not have a look myself.

**Comment by derrell** [comment]
It looks to me like previously, one would call `setVisible` to set the visibility of the *knob*. With this PR implemented, existing user code that calls `setVisible` would set the entire *slider's* visibility, not just the *knob*. I believe that with this PR, users must change their code to use `setKnobVisible` if they want to affect only the knob visibility, and not the entire slider's visibility.

(Prior to this PR, my reading indicates that there was no way to change the slider visibility because the slider's `visible` property was overridden by the one that only affected the knob; thus it was a bug and should be fixed.)

Am I reading this incorrectly?

**Comment by schnepe2** [comment]
Look at the latest release (5.0.3-beta) and you'll find no overridden `visible` property in `Splitter`.
So this whole mess was introduced in master, completely ignoring that warning.
Any application depending on that behaviour[1] is using the development (master) branch anyway.
That application can now choose! And that "ill-feature" was never a working one anyway, or how would one set the visibility of the splitter? It only allowed to change the visibility of the knob, leaving no option to choose.

Why is this such a long discussion anyway?


[1] expecting `foo.setVisible(false)` to only affect foo's Knob

**Review by level420 — APPROVED** [review]

**Review by derrell — APPROVED** [review]

**Comment by derrell** [comment]
> So this whole mess was introduced in master, completely ignoring that warning.

If that had been mentioned previously, I hadn't seen it. I thought we had a backward compatibility issue with the 5.x version, and backward compatibility is a *big deal* for most releases, thus the long discussion. Anyway, we're all set now. Thank you very much for persisting in pressing forward with this!

**Review by hkollmann — APPROVED** [review]

**Pull request merged**
