### PR TITLE
Introduce blacklist in event manager...

### LINKED ISSUE #196: Filtered item visible in List when model has been changed.
See Playground example:
http://tinyurl.com/hftbw23

Press the shift button to see the problem

A Listmodel with 5 Items where the item on index 1 is filtered. When you shift the model array the filtered Item is shown in list.

### PR DESCRIPTION
**Pull request by peuter**
... to prevent dispatching of removed events + remove bindings in virtual lists on every model change

fixes #196

### CODE REVIEW

**Comment by johnspackman** [comment]
+1

**Comment by level420** [comment]
I have two questions:

1. If I understand the code right the black list array is never emptied and grows for every removed event listener. Or am I wrong?

2. Wouldn't it be better to use a hash to speed things up? I'm bothered about the isBlacklisted method and the performance which may degrade if we have a lot of listeners. 

```javascript
// init the blacklist
this.__blacklist = {};

// add the listener uid to the blacklist
this.__blacklist[uid] = true;

// check if the listener is blacklisted
if(this.__blacklist[uid] !== true) {
  // call listener
}
```

**Comment by peuter** [comment]
There is a DeferredCall which cleans the blacklist aafter everything is done here: https://github.com/peuter/qooxdoo/blob/fix/196/framework/source/class/qx/event/Manager.js#L77

The call is scheduled when the first item has been added to the blacklist. Because of that I don't think that a hash is necessary there.

**Comment by level420** [comment]
Thank you for the explanation @peuter . 

so the code in https://github.com/peuter/qooxdoo/blob/fix/196/framework/source/class/qx/event/Manager.js#L928-L930
is meant to schedule the emptying of the blacklist until the current event listener loop has finished. Right?

I'm still not convinced about the implementation of the isBlacklisted method in https://github.com/peuter/qooxdoo/blob/fix/196/framework/source/class/qx/event/Manager.js#L941 findind blacklisted uids with indexOf, as it is called on every listener call.

But I think the idea is great and we should go wit a commit. Thank you for the PR.

**Comment by level420** [comment]
@peuter I wanted to ask if you would consider changeing the implementaion to a hash based blacklist and especially take care of performance for situations where there are no blacklisted listeners at all.
That would be really great! Thank you.

**Comment by peuter** [comment]
Ok, done.

**Comment by peuter** [comment]
> so the code in https://github.com/peuter/qooxdoo/blob/fix/196/framework/source/class/qx/event/Manager.js#L928-L930
is meant to schedule the emptying of the blacklist until the current event listener loop has finished. Right?

Yes thats right.

**Comment by level420** [comment]
Thank you @peuter ! Great!

**Comment by peuter** [comment]
One question:

Should I add an this.__blacklist.hasOwnProperty(uid) before this.__blacklist[uid] here:
https://github.com/peuter/qooxdoo/blob/fix/196/framework/source/class/qx/event/Manager.js#L945

How would that affect the performance?

**Comment by oetiker** [comment]
since bla[x] returnes undefined if x is not an existing key, I don't think testing is necessary ...

**Comment by level420** [comment]
I don't think it is needed. I'd even go with a null for this.__blacklist in the empty case and test against:

```javascript
return (this.__blacklist !== null && this.__blacklist[uid] === true)
```
without the using this.__blacklistLength.

**Comment by level420** [comment]
and in __addToBlacklist:

```javascript
if (this.__blacklist === null) {
  this.__blacklist = {};
  this.__clarBlacklist.schedule();
}
```
and clearing the blacklist would be simply setting it to null.

**Comment by peuter** [comment]
@level420 Good point, I changed it to use null checks.

**Comment by oetiker** [comment]
so it sems everyone is happy with this one :-)

**Comment by level420** [comment]
Perfect now! Let's go with this PR.

And also let's hope, that our applications do not somehow rely on the side effect that removed listeners were executed after removal. Let's see what my monster form with approx. 800 fields is doing after this commit.

**Comment by level420** [comment]
Small typo in

https://github.com/qooxdoo/qooxdoo/pull/198/files#diff-c9f3678e3bed8e09ff7b8d0919566f4dR934

'remaved' vs 'removed'

**Comment by peuter** [comment]
typo is fixed

**Comment by oetiker** [comment]
with everyone happy I merge ... thanks @peuter !

**Pull request merged**
