### PR TITLE
fix for #9293: generate pretty removes "finally", thanks to Derrell Lipman

### PR DESCRIPTION
**Pull request by hkollmann**

### CODE REVIEW

**Comment by oetiker** [comment]
I have restarted the job ... there was a timeout ...

**Review by level420 — APPROVED** [review]
Seems reasonable and simple.

**Review by johnspackman — APPROVED** [review]

**Review by derrell — APPROVED** [review]

**Review by oetiker — APPROVED** [review]

**Review by level420 — APPROVED** [review]

**Review by derrell — APPROVED** [review]

**Review by cajus — APPROVED** [review]

**Review by oetiker — APPROVED** [review]
approved again

**Review by derrell — APPROVED** [review]

**Review by oetiker — APPROVED** [review]
it is getting better and better ... love that patch

**Review by level420 — APPROVED** [review]

**Comment by level420** [comment]
5 approvals. merging.
Thank you @hkollmann

**Pull request merged**
