### PR TITLE
Revert dimension assert changes from PR #9377

### PR DESCRIPTION
**Pull request by level420**
Fixes issues reported in #9430.

### CODE REVIEW

**Review by johnspackman — APPROVED** [review]

**Review by cajus — DISMISSED** [review]

**Review by hkollmann — DISMISSED** [review]

**Review by derrell — DISMISSED** [review]

**Review by johnspackman — DISMISSED** [review]

**Review by cboulanger — DISMISSED** [review]

**Comment by johnspackman** [comment]
this can't be merged yet because the travis tests are failing - the PR being reverted added unit tests which need to be removed as part of the revert

**Review by oetiker — DISMISSED** [review]

**Review by cboulanger — DISMISSED** [review]

**Comment by hkollmann** [comment]
Seems that there are somemore tests needed to reverted

**Comment by level420** [comment]
This is not my day :-( sorry!

**Review by oetiker — APPROVED** [review]

**Review by cboulanger — APPROVED** [review]

**Review by hkollmann — APPROVED** [review]

**Review by derrell — APPROVED** [review]

**Review by johnspackman — APPROVED** [review]

**Comment by hkollmann** [comment]
6 days, 5 approvals, time to merge!
Thanks @level420!

**Pull request merged**
